### ISSUE TITLE
Rendering of one block only

### ISSUE THREAD

**Issue by fprochazka** [nette/latte#101]
I've decided to send emails using latte templates, which is working flawlesly obviously. Problem was, when I've decided that the template is a good place to store the subject too.

```latte
{block subject}subject{/block}
{block body}
Hello customer,
...
```

There is currently no easy way to do this. I was able to hack it using custom macro https://gist.github.com/fprochazka/756ab3005e5d4a750db4 - which is not nice.

---

It would be nice to have some kind of native support for this.

**Comment by hrach** [comment]
Isn't better to have a layout with a head title tag, into which you can output the subject block. Then title is automatically used as a subject.

**Comment by fprochazka** [comment]
@hrach I'm not sure I understand what you mean

**Comment by dg** [comment]
Solution is to change global functions https://github.com/nette/latte/blob/b6ffc8ce210d2cff3ccc41fc7489d51c5014c243/src/Latte/Macros/BlockMacros.php#L75 to class methods. Can you try to do it? I will not have time for it.

**Comment by fprochazka** [comment]
@dg not any time soon. Maybe someone else will. I had the same idea, but imho there has to be added api for this, since the macro has no way to escape the "render method" scope.

**Comment by kukulich** [comment]
@fprochazka This is what @hrach mean: https://github.com/nette/mail/blob/master/src/Mail/Message.php#L246

**Comment by fprochazka** [comment]
@kukulich nice feature, that might actually work. Problem is, we don't have HTML emails yet, only plaintext for now.

**Comment by enumag** [comment]
:+1: Absence of this feature forced me to use Twig to render Symfony forms.

By the way I think there already is something like this for snippets so maybe that could be used or snippets should later be rewritten accordingly.

**Comment by hrach** [comment]
@fprochazka you can easily add baic html layout and use nl2br filter on content block. nothing hard. Mail is automatically converted and sent also with text version.

**Comment by fprochazka** [comment]
@hrach I know, but I don't wanna do that right now.
