### ISSUE TITLE
Tracy & PHP error in latte template

### ISSUE THREAD

**Issue by enumag** [nette/latte#107]
When I have an error in latte template like `Call to a member function ... on array` Tracy won't show me the php code where the error occured because it was in eval. When I press F5 it shows the code like normal.

In development this could be confusing for beginners who don't know that the code will be shown on the second try. Also it is a problem in production mode where I don't have all the information needed for debugging unless the error happened two times (generating two different log entries, second contains the code).

I'm aware of the reasons behind this behavior (thx @matej21) but in my opinion this is worse than the previous bad behavior with parse errors. Also maybe we could catch the errors and add the filename to it manually for Tracy to use it?

**Comment by dg** [comment]
I am aware of that, but I do not know how to solve it.

**Comment by Majkl578** [comment]
What is the reason for eval anyway?

**Comment by enumag** [comment]
@Majkl578 From what @matej21 told me its to catch parse errors in the compiled template. Still I would rather remove it.

**Comment by dg** [comment]
It is workaround for catching parse errors in PHP < 7.

**Comment by enumag** [comment]
@dg So the eval is not used when running on PHP 7?

**Comment by Majkl578** [comment]
Well, it still is now, but it may be rewritten to not use eval: <?php

try {
    eval('non;sen-se)(');
} catch (\ParseError $e) {
    echo 'Caught: ', $e->getMessage(), "\n";
}

echo 'ok';

**Comment by dg** [comment]
Closed by f42fbe9d3ad06dc4267465e0fc8c8c833545cb2b

**Comment by Majkl578** [comment]
But eval survived... :(

**Comment by dg** [comment]
You can prepare PR, but I don't know how to simply unlink temp file later than bluescreen is displayed.
