### ISSUE TITLE
Usage outside variables in snippets

### ISSUE THREAD

**Issue by aleswita** [nette/latte#108]
Currently state:
```
{var $foo = "Hi there!"}
{snippet snip}{$foo}{/snippet}
```
Tracy: Undefined variable: foo

Sometimes a need something like below (same function as in **include** macro):
```
{var $foo = "Hi there!"}
{snippet snip, foo => $foo}{$foo}{/snippet}
```

**Comment by matej21** [comment]
This is expected behaviour. In AJAX, only invalidated snippets are executed (code inside snippet macro), so variable would not be visible.Therefore, for a consistency, you don't see outer scope inside a snippet even in non-ajax requests.
