### ISSUE TITLE
V kompilovaných latte (2.4.x) šablonách je chybka

### ISSUE THREAD

**Issue by juniwalk** [nette/latte#110]
`Warning: extract() expects parameter 1 to be array, object given in ~/temp/cache/latte/juniwalk-forms7-src-templates-schemeBuilder-latte-Template38ac8d18cf.php:117`

na tom řádku je tenhle kus kodu:

```php

	function blockSections($_args)
	{
		extract($_args);
		$_control->redrawControl('sections', FALSE);

```

**Comment by dg** [comment]
Can you investige it? I am unable to find error in this piece of code.

**Comment by juniwalk** [comment]
When I add `extract((array) $_args);`, I get error that `$_control` does not exist, I guess there is wrong set of arguments.

**Comment by juniwalk** [comment]
Also it does only in AJAX mode.

**Comment by dg** [comment]
Are you using the last nette/application 2.4.0-RC?

**Comment by juniwalk** [comment]
I should be, let me check it again.

**Comment by dg** [comment]
`composer info -i`

**Comment by juniwalk** [comment]
I had some strange mixed packages of 2.3 and 2.4, upgrade installed this: nette/application     dev-master 820414f Nette Application MVC Component

**Comment by dg** [comment]
It should work

**Comment by juniwalk** [comment]
Dammit it works now, sorry for the alarm, I had no idea composer did not upgraded everything.

**Comment by dg** [comment]
Ok
