### ISSUE TITLE
The {import} macro not working in AJAX

### ISSUE THREAD

**Issue by juniwalk** [nette/latte#111]
Hello,
I have main template and template with blocks which I import to the main template, when I click on signal to do some action and then redraw snippet, I get error 500 that block I am looking for does not exists.

Is that intended or is this issue with latte?

The error: `Undefined index: field`
```php
185:                            trigger_error('Incompatible context for including block $fieldType.', E_USER_WARNING);
186:                        }
187:                        $this->renderBlock($fieldType, ['field' => $field] + $this->params) ?>
188:    
189:    <?php
190:                    }
191:                    else {
192:                        ?>
193:    
194:    <?php
195:                        if ('html' !== $this->blockTypes['field']) { // <!-- Error is on this line
196:                            trigger_error('Incompatible context for including block field.', E_USER_WARNING);
197:                        }
198:                        $this->renderBlock('field', ['field' => $field] + $this->params) ?>
199:    

```

**Comment by juniwalk** [comment]
Defining those blocks in main template fixes this problem, so it really just does not import them when AJAX is used.

**Comment by dg** [comment]
But it did not work even with the macro `{includeblock}`, right?

**Comment by juniwalk** [comment]
Yep, did not work with {includeblock} either.

**Comment by dg** [comment]
This was really hard to solve but now should work.

**Comment by juniwalk** [comment]
Great! Thanks!
