### ISSUE TITLE
Combination of n:snippet and n:block - bug

### ISSUE THREAD

**Issue by paveljanda** [nette/latte#112]
Template:

```php
<table n:snippet="table" n:block="data">
    ...
</table>
```

Result: none.. Nothing is displayed.

When `n:block` macro is removed, the table displays correctly. Worked with v2.3.

**Comment by dg** [comment]
Interesting, I have added a special test for that :-)

**Comment by paveljanda** [comment]
(Tested on ublaboo/datagrid template)
