### ISSUE TITLE
Properties of objects in allcaps are refused during compilation time (throws user deprecated error)

### ISSUE THREAD

**Issue by foglcz** [nette/latte#113]
| |  |
|-------------------|--------------|
| **Type**          | Bug |
| **Broken versions**          | 2.4.0-RC1, dev-master |
| **OK versions**          | <= 2.3.11 |

When you have `{$variable->ANYTHING}` in your latte template, you'll get a `E_USER_DEPRECATED` error `Replace literal ANYTHING with constant('ANYTHING')`

This error is thrown at template compile time, by [`Latte\PhpWriter.php:182`](https://github.com/nette/latte/blob/master/src/Latte/PhpWriter.php#L182)

**Test code:**
```
{? $testVar1 = (object)['TESTATTRIBUTE' => 'test value 1']}
{? $testVar2 = (object)['testattribute' => 'test value 2']}
<div n:if="!empty($testVar1)">
    {$testVar1->TESTATTRIBUTE}
</div>
```

**Current result:**
```
User Deprecated

Replace literal TESTATTRIBUTE with constant('TESTATTRIBUTE')
```

In my use-case, the variable is instance of `Dibi\Row` and the all-caps attribute is a column name returned by ODBC driver, which doesn't support `COLUMN as column` syntax :smiley: :cry:

**Comment by JanTvrdik** [comment]
Related: https://github.com/nette/latte/commit/2fae04439536cd60b5d5b7223bbfc2de8335ca0c and https://github.com/nette/latte/commit/99c330c04618a61b3771d4f34936968d5f6499b6

**Comment by foglcz** [comment]
:+1: 

Confirming that this fixed the issue, thanks guys! :)

**Comment by Majkl578** [comment]
I think it still doesn't work for static properties though, does it? (It's not covered by test so it's just a guess.)

**Comment by JanTvrdik** [comment]
Static properties are ok, because they are parsed as `T_VARIABLE `, not `T_SYMBOL`

**Comment by foglcz** [comment]
Confirming that it works for all of these:

```
{App\Model\Sage\CountryCodeModel::TESTCONSTANT}
{App\Model\Sage\CountryCodeModel::TABLE_NAME}
{App\Model\Sage\CountryCodeModel::$TESTPROPERTY}
{$product::PRODUCTNUMBER}
{$product::$PRODUCTNUMBER}
{$product->PRODUCTNUMBER}
```

Works = latte compiles to php, keeping the representation. I have no idea what would `$product::PRODUCTNUMBER` actually do :))

**Comment by RisoP** [comment]
I have the same error, when namespace or class name is all caps. Not sure, if it is bug or just forcing some coding rules.

**Comment by JanTvrdik** [comment]
@RisoP Can you post an example of Latte template with such error?

**Comment by RisoP** [comment]
@JanTvrdik
`{TESTCLASS::TESTCONSTANT}`
triggers E_USER_DEPRECATED "Replace literal TESTCLASS with constant('TESTCLASS')"

`{TestClass::TESTCONSTANT}`
renders constant correctly

**Comment by dg** [comment]
fixed
