### ISSUE TITLE
Undefined variable (From forum post)

### ISSUE THREAD

**Issue by GEp1c** [nette/latte#119]
I have 3 templates merging together, **@layout.latte** for all modules:

```
<!DOCTYPE html>
<html lang="cs">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	{include #meta}
	{define meta}{/define}

	<title>{include #title} | {$setting->getValue('core.meta.title')}</title>
	{define title}{/define}
</head>
<body>
	{include #main}
	{define main}{/define}
</body>
</html>
```

Them, for example, I have module that has own **@layout.latte** defining main block from parent **@layout.latte**

```
{block meta}
    <meta name="description" content="{$meta['description']}">
    <meta name="keywords" content="{$meta['keywords']}">
    <meta name="author" content="{$meta['author']}">
{/block}

{block main}
<section id="content">
	<div class="container">
		<div class="col-md-8">
			<div class="row">
				{include #content}
				{define content}{/define}
			</div>
		</div>
	</div>
</div>
{/block}
```

And finallly, our template for each action / render:
```
{import $frontLayout}

{block title}
	{$page->title}
{/block}

{block content}
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                {$page->title} {* At this point, $page is undefined *}
                {$user->getId()} {* I also tried this, and it ends with Fatal Error (calling getId() on null)*}
            </div>
        </div>
    </div>
{/block}
```

Everything works fine, except the last block for each action / render.
Strange is, that I'm using the same layout structure in different module, **BUT** with only **1 block** defined in module **@layout.latte** (only **main block**), and **it works.**

_Or is there any other way how to correctly merge 3 layouts together?_

**Comment by dg** [comment]
Btw, why you use the combination `{include #abc}{define abc}{/define}`?

**Comment by GEp1c** [comment]
Just because I do not have to check if block exists, I just define that block in main layout and it's only on sublayout, if the block is used, or not. If I use only include, it should end with fatal error with undefined block, and if I define only define block at the same point as now, it will do nothing and block is not rendered.

**Comment by dg** [comment]
I think that you can replace i.e. `{include #meta}{define meta}{/define}` with `{block meta}{/block}`.

**Comment by GEp1c** [comment]
Works like a charm, thank you!
