### ISSUE TITLE
Import outside block with layout doesn't do anything.

### ISSUE THREAD

**Issue by hrach** [nette/latte#126]
The following code desn't include import.latte file; no exception or warning is thrown. Moving import into {block content} works. Moreover, it's affected by layout macro, without it, it works ok.

```
{layout layout.latte}
{import import.latte}
{block content}
....
{/block}
```

The reason is that the import is after `if ($this->getParentName()) return get_defined_vars();` in the main function of the template.

------

The question is how to solve it:
I suggest cosidering import as "head" macro of it's not defined in scope of block & layout is present, so it should be moved before the "if".

**Comment by dg** [comment]
This works

```php
<?php

/**
 * Test: {import ...}
 */

use Tester\Assert;


require __DIR__ . '/../bootstrap.php';


$latte = new Latte\Engine;
$latte->setLoader(new Latte\Loaders\StringLoader([
	'main' => '
		{extends parent}
		{import inc}
		{block bl}.{include test}.{/block}
	',
	'inc' => '
		{define test}Test{/define}
	',
	'parent' => '
		Parent
		{include bl}
	',
]));

Assert::match(
	'Parent
.Test.',
	trim($latte->renderToString('main'))
);
```

**Comment by dg** [comment]
@hrach can you prepare failing test?
