### ISSUE TITLE
Display the key of an array by Smarty-like way

### ISSUE THREAD

**Issue by debute** [nette/latte#128]
If you know Smarty template engine, then you know that you can access to the key of any array like with objects in JavaScript. Example: **{$myArray.myKey}**
This one is (in my opinion) realy good idea, so I tried to apply it to the Latte template engine. In file **Latte\Loaders\FileLoader.php** at line 50, on the return I'm sending template data through function **compileArrays()**.

I think this would be good advantage for Latte, so that's why I'm writing this issue. I know that maybe my function is not the best, but it is working almost at everything, where I'm using arrays. So, here is the function: [compileArrays.zip](https://github.com/nette/latte/files/399573/compileArrays.zip)

**Comment by dg** [comment]
Thanks. 

Native support in Latte for this syntax is not yet planned.
