### ISSUE TITLE
Makro form v Latte 2.4 nedefinuje $formContainer

### ISSUE THREAD

**Issue by dakujem** [nette/latte#133]
Preco makro `{form }` nedefinuje premennu `$formContainer`, rovnako ako makro `{formContainer }`?

Ak som v predoslom Latte mal sablonove bloky, ktore vypisovali skupiny inputov, bolo jedno, ci som blok inkludoval z formu alebo z kontajneru, jednoducho sa vsade pouzivala premenna `$_form`. Teraz je nutna kontrola (alebo vlastna uprava makra `form`).

**Comment by dg** [comment]
For support use please http://forum.nette.org or https://gitter.im/nette/nette/cs, this is issue tracker in English.
