### ISSUE TITLE
Ignoring dynamic children snippets and sending only the parent snippet.

### ISSUE THREAD

**Issue by hrach** [nette/latte#135]
In Nextras Datagrid, the table are wrapped in `{snippet table}` and particular rows are in a dynamic snippet `{snippet row-$id}`. 

For the grid, I would use functionality, which sometimes switch the behavior: for pagination I'd like to send the whole `table` snippet, for inline row editation I'd like to send only the `row-$id` snippet.

In earlier version of Latte, it was possible to hack it via [modifying the $_dynSnippets variable](https://github.com/nextras/datagrid/blob/v2.1.3/src/Datagrid.latte#L191-L195) (+ line 182, 186). Currently, I'm hacking it [this way](https://github.com/nextras/datagrid/blob/master/src/Datagrid.latte#L176-L190), but neither of these hacks seem pretty and some general solution in Latte would be great.

**Comment by matej21** [comment]
The most common solution is to wrap it into an another static snippet. But I agree it would be great to have this feature. 

Do you have any idea how the API in a control should look like? Add another parameter to a redrawControl?

**Comment by hrach** [comment]
>The most common solution is to wrap it into an another static snippet. 

Huh, if it's work, it seem to be a lot better solution without internal hacks.

**Comment by hrach** [comment]
> Do you have any idea how the API in a control should look like? Add another parameter to a redrawControl?

Not sure at all :| But it sounds usable :-)
