### ISSUE TITLE
Content type HTML should be allowed inside of HTMLCOMMENT type.

### ISSUE THREAD

**Issue by vhenzl** [nette/latte#136]
With Latte 2.4 I've run into problems with blocks inside of (conditional) HTML comments.

Let's say, I have `@layout.latte` template like this:

```html
<body>
  {include content}
  <!--[if IE]>
    {block onlyIE}{/block}
  <![endif]-->
</body>
```

If I override `onlyIE` block in a page template I get **User Warning**: `Overridden block onlyIE with content type HTMLCOMMENT by incompatible type HTML.`
Also, I get similar warning if I try to include a block: `Including block onlyIE with content type HTML into incompatible type HTMLCOMMENT.`

IMO, there isn't any reason this shouldn't be allowed. Is it?

**Comment by dg** [comment]
Reason is that in comments is differently escaped character `-`.  

(btw conditional comments are not supported since IE 10)

**Comment by vhenzl** [comment]
Oh, I didn't know about IE 10. But that was just an example. In fact, I need it for more obscure conditions as `[if mso]` in e-mail templates. Anyway, thanks a lot.
