### ISSUE TITLE
Length of the cached templates

### ISSUE THREAD

**Issue by debute** [nette/latte#137]
Converted templates have names containing of the 2 previous folders. For example: `Default-views-index.html--4e31f47114.php`. That's good to determine original file. But I have one file `/admin/Default/views/index.html` and second `/dashboard/Default/views/index.html`, which in result have same cache name. So everytime I visit home page in the admin and then come back to dashboard, it updates the cache file again, even it was not changed. Is it possible to create name from 3 folder parents?

**Comment by dg** [comment]
Hash code `4e31f47114` is the same too?

**Comment by debute** [comment]
I looked at it again and now there are 2 different hash codes. I guess, that the hash code is generated by the time of file edit, right? Because I was copying it from other project (saves the time, when template is same). But when they are changed at different times, hash code is different too.

**Comment by dg** [comment]
Hash code is generated from file name.

**Comment by debute** [comment]
Ohh, ok. But it is possible to have "longer cache names"? Probably I'm the only one using that much of same names for folders :)

**Comment by dg** [comment]
So is there a problem with updating cache or is not?

**Comment by debute** [comment]
I don't think so, you can close this issue. But if there would be such a feature to change behavior of cache names, it would be great.

**Comment by dg** [comment]
The question is, how long it should be.

**Comment by debute** [comment]
Instead of 2 parent folders' names it should contain 3.
