### ISSUE TITLE
FileLoader::normalizePath() strips leading ../

### ISSUE THREAD

**Issue by spaze** [nette/latte#138]
First, thanks for making Latte! ☕ 

While migrating to Latte 2.4 I've find the following issue, if I do this in a presenter:

```
$this->createTemplate()->setFile('../../foo/bar.latte);
```

and there's
```
{include waldo.latte}
```

in `bar.latte`, rendering fails with

***RuntimeException: Missing template file foo/waldo.latte***

I've tracked it down to an issue in [`Latte\Loaders\FileLoader::normalizePath()`](https://github.com/nette/latte/blob/003e4849365e28d4a78bef42c2c2e071d647c526/src/Latte/Loaders/FileLoader.php#L87-L98) where in the first [`foreach`](https://github.com/nette/latte/blob/003e4849365e28d4a78bef42c2c2e071d647c526/src/Latte/Loaders/FileLoader.php#L90) iteration when `$res` is still empty then if it hits [`$part === '..'`](https://github.com/nette/latte/blob/003e4849365e28d4a78bef42c2c2e071d647c526/src/Latte/Loaders/FileLoader.php#L91) condition then the `$part` is just thrown away because it tries to [`array_pop`](https://github.com/nette/latte/blob/003e4849365e28d4a78bef42c2c2e071d647c526/src/Latte/Loaders/FileLoader.php#L92) from an empty array.

The issue can be demonstrated by adding
```
Assert::same('../../tests', $loader->getReferredName('../tests', '../file'));
```
to [Loaders.FileLoader.phpt](https://github.com/nette/latte/blob/003e4849365e28d4a78bef42c2c2e071d647c526/tests/Latte/Loaders.FileLoader.phpt
).

Hope this is at least a bit understandable.

The workaround is to never pass leading `../` to `setFile()` (and use `realpath()` to remove these) but since I've already spent quite a while figuring out where's the problem, the proposed fix is an incoming pull request.

**Comment by OzzyCzech** [comment]
Have same problem after upgrade to 2.4

**Comment by dg** [comment]
`$this->createTemplate()->setFile('../../foo/bar.latte);` seems like code smell (i.e. relative paths are code smell), you should use absolute path.

**Comment by OzzyCzech** [comment]
I know (do not agree) but It should work - it's valid path and valid use case

**Comment by dg** [comment]
I agree that normalizePath should be fixed, but still I have to point out that using relative paths is a security problem and you should never use them :)

**Comment by spaze** [comment]
@dg Thanks! Why is that a problem?

**Comment by dg** [comment]
Because you never know against *what* it is relative.

**Comment by spaze** [comment]
Sure, it's always current directory which can be changed, of course. Maybe I just misunderstood what you said and thought you mean it *always* is a problem, sorry. It's clear now, thanks.

**Comment by spaze** [comment]
Just a side note, this discussion made me revisit my initial workaround for the original issue and realizing I'd need to work around it *harder* I've moved my files elsewhere, which made the code easier and solved the issue for me. So yeah, a happyend, thanks @dg :-)
