### ISSUE TITLE
Missing way to use control constants as snippet/snippetArea name

### ISSUE THREAD

**Issue by mstefan21** [nette/latte#141]
We are using control constants to define control names for better orientation in the project code. Unfortunately currently there is no way to do same thing with the snippet. For example:

``` php
namespace Vendor\App;

class ExampleForm extends Nette\Application\UI\Form
{

    const CONTROL_SUBMIT = 'submit';
    const SNIPPET_FORM = 'form';

    public function __construct()
    {
        $this->addSubmit(self::CONTROL_SUBMIT, 'submit')
            ->onClick[] = array($this, 'handleSubmit');
    }

    public function handleSubmit(SubmitButton $button)
    {
        $this->onSubmit($button);
        $this->redrawControl(self::SNIPPET_FORM);
    }

}
```

``` latte
{form $control::CONTROL_FORM}
    <div n:snippet="$form::SNIPPET_FORM">
        {input $form::CONTROL_SUBMIT}
    </div>
{/form}
```

or

``` latte
{form \Vendor\App\ExampleControl::CONTROL_FORM}
    <div n:snippet="\Vendor\App\ExampleForm::SNIPPET_FORM">
        {input \Vendor\App\ExampleForm::CONTROL_SUBMIT}
    </div>
{/form}
```

This example unfortunately will throw the following exception:
[Dynamic snippets are allowed only inside static snippet/snippetArea.](https://github.com/nette/latte/blob/master/src/Latte/Macros/BlockMacros.php#L222)

**Comment by zeleznypa** [comment]
:+1:

**Comment by TomasVotruba** [comment]
That probably means the code has to be wrapped in `{snippet}`:

```latte
{snippet}
    {form \Vendor\App\ExampleForm::CONTROL_FORM}
        <div n:snippet="$form::SNIPPET_FORM">
            {input $form::CONTROL_SUBMIT}
        </div>
    {/form}
{/snippet}
```

Could you try that?

**Comment by mstefan21** [comment]
This was just an example. We need to redraw the specific part, not the whole control.

```latte
{form \Vendor\App\ExampleForm::CONTROL_FORM}
	<div n:snippet="$form::SNIPPET_FORM">
		{input $form::CONTROL_SUBMIT}
	</div>
	<div n:snippet="$form::SNIPPET_WE_DONT_WANT_REDRAW">
		{* some big satic data *}
	</div>
{/form}
```

**Comment by dg** [comment]
It is dynamic snippet, because value of `$form` is unknown.

**Comment by mstefan21** [comment]
$form|$control is uknown, but we can use static constant like this, but it also doesn't work, because the `\Vendor\App\ExampleControl::CONTROL_FORM` is interpreted as a string instead of the constant value.

```latte
{form \Vendor\App\ExampleControl::CONTROL_FORM}
	<div n:snippet="\Vendor\App\ExampleForm::SNIPPET_FORM">
		{input \Vendor\App\ExampleForm::CONTROL_SUBMIT}
	</div>
{/form}
```

**Comment by dg** [comment]
Possible solution is to pass variable `$formName = Vendor\App\ExampleControl::class` and then use `<div n:snippet="$formName::SNIPPET_FORM">`

**Comment by micha-walter** [comment]
I have test this, but it's not working. Same Error as above with this tests:
```
<div n:snippet="\Vendor\App\ExampleForm::SNIPPET_FORM">
```
or
```
{var $formName = Vendor\App\ExampleControl::class}
<div n:snippet="$formName::SNIPPET_FORM">
```
My packages are:
```
latte/latte: v3.0.9
nette/application: v3.1.13
```

Is there a chance that this will be supported in the future?

I used the constants in my code to redraw the controls, so the strings of `n:snippet` in template and `$this->getComponent(\Vendor\App\ExampleForm::SNIPPET_FORM)->redrawControl()` in Presenter should always the same.
