### ISSUE TITLE
Nonoptimal error message when latte file contains {...}

### ISSUE THREAD

**Issue by EdaCZ** [nette/latte#145]
I noticed that when you write `{...}` to some latte template, error message is not very clear.

![undefined macro](https://cloud.githubusercontent.com/assets/1671637/19840956/365fd9d4-9f02-11e6-90f2-7b8e7f516993.png)

I think error message should be something like "Undefined macro '...'".

It has very low priority but I wanted to note it somewhere, so I created this issue.

**Comment by dg** [comment]
Fixed in Latte 3
