### ISSUE TITLE
Incorrect enclosing of string inside javascript strings

### ISSUE THREAD

**Issue by josefsabl** [nette/latte#149]
- bug report? yes (at least I think so :)
- feature request? no
- version: 2.4.2

### Description
String variables are enclosed by `&quot;` even if inside quotes already (string) in Javascript generating duplicate quotes resulting in unwanted quotes inside string (in better case) or even broken Javascript.

### Steps To Reproduce
```
{var $world = "World"}

<button onclick="alert('Hello {$world}!')">HW</button>
<button onclick='alert("Hello {$world}!")'>HW</button>
```

generates

```
<button onclick="alert('hello &quot;World&quot;')">HW</button> displays Hello "World"! (notice the unwanted quotes)
<button onclick='alert("hello &quot;World&quot;")'>HW</button> generates syntax error
```

**Comment by JanTvrdik** [comment]
The code you have written is incorrect, it should be 

~~~html
{var $world = "World"}

<button onclick="alert('Hello ' + {$world} + '!')">HW</button>
<button onclick='alert("Hello " + {$world} + "!")'>HW</button>
~~~

**Comment by josefsabl** [comment]
Thanks for the response. So it is not a bug but missing feature?

It definitely does not respect this claim from [docs](https://latte.nette.org/en/#toc-context-aware-escaping): **All is done automatically, consistently and correctly.**

The resulting HTML is not okay either: `<button onclick="alert('Hello ' + $quot;World$quot; + '!')">HW</button>` vs `<button onclick="alert('Hello World!')">HW</button>`

And also note that latte is templating engine and imho shouldn't require changes to the surrounding code. From this perspective this behavior is non-standard at least. In other templating language (PHP e.g. ;) you can definitely write:

`<button onclick="alert('Hello <?= htmlspecialchars($world) ?>!')">HW</button>`

It will work just fine and you wouldn't need to change JS code itself.

Just asking, no offence intended :-)
<3

**Comment by dg** [comment]
> you can definitely write:
> <button onclick="alert('Hello <?= htmlspecialchars($world) ?>!')">HW</button>

You can, but it is XSS. `$world` can contain `'); destroyComputer('`.

It's true that this is missing in documentation, could you please add it?

**Comment by josefsabl** [comment]
Ehh, sure, that is why I use latte :1st_place_medal: 

doc: can do

**Comment by josefsabl** [comment]
Anyways, the fact that there is XSS in my example doesn't render the rest of comment invalid, does it? :-)

**Comment by dg** [comment]
This is just a limitation. To overcome it someone have to implement JavaScript parser into Latte. It probably never happend.

**Comment by josefsabl** [comment]
Got it. Thanks!

**Comment by milo** [comment]
Is there some possibility to detect it and throw warning?

**Comment by dg** [comment]
Yes, for simple cases like `<button onclick="alert('{$world}!')">` it throws warning.

**Comment by dg** [comment]
If someone wanted to create JS parser, here is inspiration https://php.vrana.cz/minifikace-javascriptu.php.  It doesn't support http://es6-features.org/#StringInterpolation
