### ISSUE TITLE
Make include work without .latte extension 

### ISSUE THREAD

**Issue by rolandtoth** [nette/latte#153]
- bug report? no
- feature request? yes
- version: 2.4.3

### Description

It would be nice to be able to optionally omit ".latte" extension in includes, eg.

`{include 'header'}`

instead of 

`{include 'header.latte'}`

**Comment by JanTvrdik** [comment]
`{include 'header'}` includes `{block header}`

**Comment by rolandtoth** [comment]
Sorry, wasn't aware of that it includes a block. However, using it with quotes tries to include a file `Missing template file...`, without quotes a block `Exception: Cannot include undefined block ....`. But I agree it's better to explicitly use an extension this case.
