### ISSUE TITLE
Anchors do not work when language is set to EN

### ISSUE THREAD

**Issue by vohratom** [nette/latte#155]
- bug report? yes
- feature request? no
- version: 2.4 

### Description
None of the anchor hyperlinks works when browsing nette in english version.

Steps To Reproduce
1. Go to https://latte.nette.org/en/macros
2. Click to any hyperlink e.g. "foreach loop"
3. Observe the issue (page is not scrolling down to the section)

Additional info:
Minor issue

**Comment by dg** [comment]
Closed d2fee66b411a84d73ee34e210ca61d967b1e8f09
