### ISSUE TITLE
Failed tests with PHP 7.2.0-dev

### ISSUE THREAD

**Issue by remicollet** [nette/latte#162]
- bug report? yes
- feature request? no
- version: 2.4.4

### Description
Yes, quite "early" report

```
 _____ ___  ___ _____ ___  ___
|_   _/ __)( __/_   _/ __)| _ )
  |_| \___ /___) |_| \___ |_|_\  v2.0.x

PHP 7.2.0-dev (cli) | php72 | 8 threads

s.FF....FF..FFFFF..FFF.FF....F..F.......F....F...F.F....F..FFF.F.FF.FFF..F..F..F...........F......................FF..F.FFFFF.F..F.FFFFFFFFFFF

-- Skipped: Latte\Engine & parseError | tests/Latte/Engine.parseError.phpt
   Requires PHP < 7.

-- FAILED: Latte\Engine and Texy. | tests/Latte/BlockMacros.block.texy.phpt
   Exited with error code 255 (expected 0)
   Latte\CompileException: Unknown macro {}, did you mean {l}?

etc
```

Will be nice to have "nightly" enabled in travis.

**Comment by Majkl578** [comment]
Isn't this caused by BC break in ext/pcre (https://github.com/php/php-src/pull/1303)? I'd wait for https://github.com/php/php-src/pull/2526 to get resolved.

**Comment by dg** [comment]
I'll enable tests for 7.2 in September or October.

**Comment by remicollet** [comment]
> Isn't this caused by BC break in ext/pcre (php/php-src#1303)? I'd wait for php/php-src#2526 to get resolved.

Indeed, test suite ok with latest 7.2.0-dev snapshot
