### ISSUE TITLE
Inconsistent syntax: {$foo} vs. {"foo"}

### ISSUE THREAD

**Issue by jkufner** [nette/latte#166]
- bug report? yes
- feature request? yes
- version: 2.4.2

### Description

`{"foo"}` does not work, but `{var $foo = "foo"}{$foo}` works.

Workaround: `{="foo"}`, but then `{=$foo}` should be mandatory as well.

I would expect the syntax to be `{expression}`, where the `expression` can be variable, string, or anything else. For example `{$foo."bar"}` produces `foobar`. The need for `{=expression}` in some cases while it is not needed in other is wierd.

Proposition: Make `{"foo"}` work.

BC break: none.

### Steps To Reproduce

Printing a variable works as expected:

    {var $foo = "foo"}
    {$foo}

The result is `foo`.

But printing a string without variable does not work:

    {"foo"}

The result is `{"foo"}` (including brackets and quotes).

**Comment by JanTvrdik** [comment]
This is a BC break, the current behavior is AFAIK intentionally designed to increase interoperability with JavaScript.

**Comment by CZechBoY** [comment]
I don't get why to do this. Why to do ```php <?php echo "foo"; ?>``` when I can print it without php? ```html foo```

**Comment by dg** [comment]
As @JanTvrdik said, it is intentionally, for compatibility with JavaScript and JSON.
