### ISSUE TITLE
Regex for macro matching does not match nested curly braces

### ISSUE THREAD

**Issue by stano** [nette/latte#167]
It is not possible to write some complex php code (I know that it is not best practice, but sometimes needed).

Example:
```
{php
  if (true) {
    if (true) {
    }
  }
}
```
https://github.com/nette/latte/blob/babc8567181a6a673803696076234c652f7a1c4f/src/Latte/Compiler/Parser.php#L272

**Comment by CZechBoY** [comment]
Could not you use default Latte macros for `{if}`? You can nest them as you want.

**Comment by stano** [comment]
Yes, I can. Thank you for the tip.
But it could be good to mention this limitation in latte docs for php macro.
I am not skilled in writing good english. (A ani česky by som to gramaticky správne nenapísal).
