### ISSUE TITLE
"AND" keyword in "if" macro

### ISSUE THREAD

**Issue by nechutny** [nette/latte#172]
- bug report? maybe
- feature request? no
- version: 2.4

### Description
Hello,

I'm migrating one old project from Nette 2.2-dev to 2.4 and i've realized that new latte doesn't support "AND" keyword in if condition. I can't find any reason why it was removed. Documentation says "Conditions behave exactly the same way as their PHP counterparts". Modify all templates to use "&&" was pain and in my opinion "AND" is more readable. Is it bug, or just change which isn't noted in documentation? It's inconsistent, because keyword "OR" is in IF allowed.

### Steps To Reproduce
Latte: {if $a AND $b}...{/if}

**Comment by dg** [comment]
They are supported only in lowercase.
