### ISSUE TITLE
feature request: "template override" - including template by searching multiple directories

### ISSUE THREAD

**Issue by badpenguin** [nette/latte#174]
- bug report? no
- feature request? yes
- version: 2.4.7

### Description
When including a template is it possibile to search it inside multiple directories?
I want to allow template override on a shared installation.

If its not currently possibile. Will writing a custom FileLoader solve my problem?

**Comment by dg** [comment]
That's exactly what should solve custom FileLoader.

**Comment by badpenguin** [comment]
Thanks, i'll try to look at the source and implement one myself.

**Comment by jelen07** [comment]
I found this issue so I'm not creating the new one.
# Add support for template overriding

**Allow developers** to **override any template** in a project. Templates of presenters, components, extension's presenters and components, etc.

It would be **really useful** to have a feature like this supported in Latte by default.

Discussions of some earlier (immature) solution's [ about this topic ](https://github.com/68publishers/application/issues/3)in Czech and [it's implemented solution](https://github.com/68publishers/application/commit/a174c689a0c1c907a1e9ebdef475db4e7d70d7c9).

How much would it cost have feature like this?

**Comment by badpenguin** [comment]
I did with  custom FileLoader as suggested, no need to implement one.

**Comment by mabar** [comment]
I have [own implementation](https://github.com/modette/cmf/commit/62e95749df376eb717d87f31476bd812dfe35a6e) too, imho it's too complex and too specific problem to be solved by Nette as most of it's users just don't need it.

**Comment by jelen07** [comment]
Some other frameworks have this feature by default and it's really powerful. There could be a standard implementation that everyone can profit from. It's about the point of view - I'm not saying that is not too complex, but rather than specific I would say general problem.
Now you have to hack latte to achieve this. When you use some solution, it isn't compatible with ours.
