### ISSUE TITLE
Default value for Compiler macros

### ISSUE THREAD

**Issue by f3l1x** [nette/latte#176]
- bug report? no
- feature request? yes
- version: 2.4.x

### Description

We're writing template processing with Latte\Engine. We have defined our custom Compiler and it has ho macros. At this time it's not possible, because [`Compiler::$macros`](https://api.nette.org/2.4/source-Latte.Compiler.Compiler.php.html#$macros) has no default value.

I'm not sure it's bug a or feature (Compiler could live without any macro?).

I can prepare PR in case.

**Comment by dg** [comment]
PR would be fine

**Comment by f3l1x** [comment]
Closed via https://github.com/nette/latte/pull/177
