### ISSUE TITLE
Bad parsing self-closing syntax for empty element

### ISSUE THREAD

**Issue by mrcnpdlk** [nette/latte#179]
Version: 2.4.7

### Bug Description
Problem with self-closing syntax (`<Foo/>`) for empty element where `Foo` is string with underscore character. Output of `renderToString()` method is damaged.

### Steps To Reproduce
Input:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<MAIL_Sender/>
<MAIL_Receiver/>
<MAIL_Subject/>
<MAIL_Smtp_Server/>
```
Output method of `renderToString()`
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<MAIL_Sender></MAIL>
<MAIL_Receiver></MAIL>
<MAIL_Subject></MAIL>
<MAIL_Smtp_Server></MAIL>
```

### Expected Behavior
Bug fix.

### Possible Solution
I've no idea. Maeby some regexp in Parse class.

**Comment by dg** [comment]
IMHO `<MAIL_Sender/>` and `<MAIL_Sender></MAIL>` is the same.
