### ISSUE TITLE
 PHP Fatal error:  Uncaught Error: Class 'Latte\Engine' not found

### ISSUE THREAD

**Issue by brada1703** [nette/latte#190]
Version: 2.5.1

### Bug Description

PHP Fatal error:  Uncaught Error: Class 'Latte\Engine' not found 

### Steps To Reproduce

Install Latte\Latte with composer
`$latte = new Latte\Engine; ` within the submission file (php)
using PHP 7.2

### Expected Behaviour

It would pass

**Comment by mabar** [comment]
https://getcomposer.org/doc/01-basic-usage.md#autoloading

**Comment by brada1703** [comment]
@mabar , do you mind giving me some more thoughts about this? I have tried to require the autoload file, which, unfortunately, has not solved the problem.

**Comment by brada1703** [comment]
Solved:

`composer dumpautoload`

then changed 

```
        "nette/mail": "2.4.*",
        "latte/latte": "2.4.*",
```

Then, 

`composer up --ignore-platform-reqs`
