### ISSUE TITLE
Unable to apply custom filter to string constant

### ISSUE THREAD

**Issue by andrei-dascalu** [nette/latte#192]
Version: 2.4.8

### Bug Description
When declaring a custom filter and applying it to a string constant, the construct is not interpreted and instead it's rendered as-is.

### Steps To Reproduce
```php
        $template->addFilter('playFilter', function($string) {
            return sprintf('played-%s', $string);
        });
```

```html
{'test'|playFilter}
```

### Expected Behavior
Output: `played-test`

### Actual Behavior
Output: `{'test'|playFilter}`

**Comment by dg** [comment]
This behavior is intentional to allow JavaScript / JSON be easily written in template. Solution is `{='test'|playFilter}`
