### ISSUE TITLE
Define redraw as snippet in ajax request

### ISSUE THREAD

**Issue by MartkCz** [nette/latte#193]
Version: 2.5.2

Component:
```php
	public function handleSnip(int $account): void {
		$this->redrawControl('profiles');
	}
```

template:
```html
{define _xxx}
	<input n:name="xxx">
{/define}

<a n:href="snip!">Ajax</a>
```

In normal request _xxx is not called, but in ajax request is called by SnippetDriver. Probably name is problem (when _xxx is renamed to xxx, ajax request is ok), specifically _

PS: function name in generated php file is blockXxx instead of block_xxx

**Comment by dg** [comment]
The problem is actually in the title, the underscore at the beginning is used internally for snippets.

**Comment by MartkCz** [comment]
So can latte throw exception if block starts with undescore?
