### ISSUE TITLE
The output is snipped after the include macro or inside the included template.

### ISSUE THREAD

**Issue by josefsabl** [nette/latte#195]
Hello, I believe [this](https://github.com/nette/latte/commit/0050781e844ecd295cebc8db21f652dfcac7e410) commit introduced some strange bug.

This commit is the first in the 2.5.2 series where I observe the following. It is hard for me to really isolate or even describe the problem, but it seems like the output of the page is snipped after last included template.

I have a template with the named argument and the page is snipped in the middle of the template where the argument is used.

If I remove the argument from the template, the page is snipped at the end of the included template.

When I remove the include altogether the page is snipped after the previous included template.

Is there anything I should look for to isolate or describe the problem better?

**Comment by dg** [comment]
Can you try if this https://github.com/nette/latte/commit/276c39052129ef32a084d55156b4d3db2e377466 fixed this problem?

**Comment by josefsabl** [comment]
Sorry for the delay, I was out for some time.

And YES! The commit fixes the problem. I assume it will get to a new version anytime soon. Think I will wait for it :-) Thank you very much.

**Comment by dg** [comment]
I released it as v2.5.3
