### ISSUE TITLE
extend filter method safeUrl

### ISSUE THREAD

**Issue by geniv** [nette/latte#203]
I found an interesting thing, the **safeUrl** method leaves _http_ / _https_ / _ftp_ and _mailto_ protocols in the url. Personally, I think there may be other exceptions nowadays, for example: _tel_ / _callto_ / _sms_ (and even _fax_) / _skype_ / _whatsapp_ / _market_ / _callto_; so there is no need to use a solution like "nocheck".

source:

https://css-tricks.com/the-current-state-of-telephone-links/

https://digitalfortress.tech/tricks/creating-direct-click-to-call-sms-links/

https://beradrian.wordpress.com/2010/01/15/special-links/

**Comment by dg** [comment]
Good idea, I will add tel: & sms: yet.
