### ISSUE TITLE
Invalid code for ternary operator

### ISSUE THREAD

**Issue by kukulich** [nette/latte#208]
Version: 2.6.0

### Bug Description
Version 2.6.0 generates invalid PHP code for ternary operator.

### Steps To Reproduce
Latte code

```
{var $zoom = $firstClaimLocation->accommodation ? \Slevomat\Partner\Profile\Premise\PartnerProfilePremise::MAP_ZOOM_ACCOMMODATION : \Slevomat\Partner\Profile\Premise\PartnerProfilePremise::MAP_ZOOM_DEFAULT}
```

generates

```php
$zoom = ($firstClaimLocation->accommodation ?? null) \Slevomat\Partner\Profile\Premise\PartnerProfilePremise::MAP_ZOOM_ACCOMMODATION : \Slevomat\Partner\Profile\Premise\PartnerProfilePremise::MAP_ZOOM_DEFAULT;
```

### Expected Behavior
It should generate (as in previous versions):

```php
$zoom = $firstClaimLocation->accommodation ? \Slevomat\Partner\Profile\Premise\PartnerProfilePremise::MAP_ZOOM_ACCOMMODATION : \Slevomat\Partner\Profile\Premise\PartnerProfilePremise::MAP_ZOOM_DEFAULT;
```

**Comment by dg** [comment]
Fixed. Purely out of curiosity, why so many people use leading slashes in templates?

**Comment by kukulich** [comment]
Both version works and no CS tool for latte :)

**Comment by hrach** [comment]
> Fixed. Purely out of curiosity, why so many people use leading slashes in templates?

Since I know it generates a PHP file and don't remember if it has any namespace :)
