### ISSUE TITLE
Update template in production

### ISSUE THREAD

**Issue by matronator** [nette/latte#209]
Hi! Totally new to this stuff, but I was asked to make some minor changes on a website that runs on Nette/Latte. So I edited the appropriate '.latte' file and pushed it back on to the server, but the template page haven't changed.

Is it possible to change templates "on the run" or do I have to download the entire project and recompile it locally?

**Comment by mabar** [comment]
In the production mode (`$configurator->setDebugMode(false)`) files are not checked for changes as you should never change code directly at production server.
Correct approach is delete of cache during deployment. It will then generate new compiled template with your changes.
Btw, for questions is preferred to use [forum](https://forum.nette.org)

**Comment by matronator** [comment]
Deleting cache did it, thanks! :)
