### ISSUE TITLE
Undefined variable when using ternary operator

### ISSUE THREAD

**Issue by badpenguin** [nette/latte#222]
Is there a way to stop the phpstorm plugin from signaling warning "undefined variable" for variables used this way:
```{$tag_html ?: '<html>' |noescape}```

**Comment by dg** [comment]
It works the same way as in PHP. You can use `{$tag_html ?? '<html>' |noescape}`

**Comment by badpenguin** [comment]
> It works the same way as in PHP. You can use `{$tag_html ?? '<html>' |noescape}`

Yes I did but the phpstorm plugin is complaining. I'm forced to add a {default ....} everywhere?

**Comment by dg** [comment]
Look at this blogpost https://blog.nette.org/en/latte-how-to-use-type-system
