### ISSUE TITLE
Native boolean rewriter to string

### ISSUE THREAD

**Issue by janbarasek** [nette/latte#224]
Hello,

I would like to have a filter that converts a boolean to a string.

For instance I want type this code for call Vue component:

```html
<product-stock
    :is-variant="{$product->isVariant() ? 'true' : 'false'}">
</product-stock>
```

And the ternary operator code doesn't look good. I think this feature can be native behavior of Latte.

If you think this is a good idea, I will implement the filter and send PR.

Thanks.

**Comment by dg** [comment]
That already exists and it's called `|escapeJs`.
