### ISSUE TITLE
Custom macro which starts with underscore

### ISSUE THREAD

**Issue by awps** [nette/latte#226]
Version: 2.8.1

### Bug Description
I'm trying to create a macro which is starting with an underscore and it fails on thinking that it's a translation.

Also using a php function that starts with underscore fails as well.

In my case I'm trying to use this function `__()`: https://developer.wordpress.org/reference/functions/__/

Using the function directly or creating a macro, the problem still persists.

### Steps To Reproduce

```latte
<a href="#" class="button">{__('Get an estimation', 'domain')}</a>
```

 ```php
$this->latte->addFunction('__', [$this, '__']);
//...
public function __($text, $domain = 'default')
{
    return __($text, $domain);
}
```

### Expected Behavior
Should execute the actual function `__()`, not trying to use the translation filter.

I'm using only the `Latte` engine and `Tracy`, without `Nette` framework.

The actual error: 
![image](https://user-images.githubusercontent.com/1436534/83733643-7a735b00-a656-11ea-9d6a-4cef8e56c2e1.png)

### Another question:
Is, it possible to remove this macro: **`_`** ?

**Comment by dg** [comment]
`{_` macro is a historical relic that cannot be removed now due to backward compatibility until version 3.0.

But you can use `{=...}` to call functions without any restrictions, so for example `{=__('Get an estimation', 'domain')}`.

**Comment by awps** [comment]
Oh! Good to know that I can call functions this way. :)
Thank you for your help.
