### ISSUE TITLE
escapeJs generates invalid JSON

### ISSUE THREAD

**Issue by ondrejmirtes** [nette/latte#231]
Cross-posting from: https://github.com/nette/utils/issues/235#issuecomment-700641924

This code:

```php
str_replace([']]>', '<!'], [']]\x3E', '\x3C!'], $json);
```

Needs to be:

```php
str_replace([']]>', '<!'], ["]]\x3E", "\x3C!"], $json)
```

In order to produce valid JSON. Please double-check after me, but when I tried the first version, `JSON.parse` in the browser complained about an `unexpected character` because of literal `\x3` in there.

**Comment by dg** [comment]
Fixed

**Comment by ondrejmirtes** [comment]
Thank you.
