### ISSUE TITLE
{control} is not context-escaped

### ISSUE THREAD

**Issue by dakur** [nette/latte#232]
Version: 2.8.1

### Bug Description
When you render component with `{control X}` inside of `<script>` tag, it is not properly escaped, but left as-is instead.

### Steps To Reproduce

`TrackerFactory.php`
```php
interface TrackerFactory
{
  public function create(): Tracker;
}
```

`Tracker.php`
```php
final class Tracker extends Control
{
  public function render(): void
  {
    echo $this->link('track');
  }

  public function handleTrack(): void
  {
    // ...
  }
}
```

Presenter:
```php
private TrackerFactory $trackerFactory;
public function createComponentTracking(): Tracker
{
  return $this->trackerFactory->create();
}
```

Template:
```html
<script>
  window.initializeApp(
    {control tracking}
  );
</script>
```

Script: (just to mention use-case)
```js
export function initalizeApp(trackingLink)
{
  // ...
  window.setInterval(() => sendDataToBackend(trackingLink, data), 10000);
  // ...
}
```

### Buggy Behavior
Output in template:
```html
<script>
  window.initializeApp(
    /neco/neco?do=tracker-track
  );
</script>
```

Notice missing quotes `"` and unescaped slashes `/`.

### Expected Behavior
Output in template:
```html
<script>
  window.initializeApp(
    "\/neco\/neco?do=tracker-track"
  );
</script>
```

### Possible Solution
Just workaround:
```html
{capture $trackingLink}{control tracking}{/capture}
<script>
  window.initializeApp(
    {$trackingLink}
  );
</script>
```

**Comment by JanTvrdik** [comment]
Control is expected to render html.

**Comment by dakur** [comment]
We should mention it [in the docs](https://doc.nette.org/en/3.0/components#toc-rendering) in such case.

But is there any reason for it? Can not we support other contexts as well?

**Comment by JanTvrdik** [comment]
Maybe `macroControl` could throw exception when `{control}` is used in non-html context?

**Comment by dakur** [comment]
Yeah, that can be a solution. But why can not be `{control}` used in other contexts as well?

**Comment by milo** [comment]
For that, `$control->render()` would have to return context of rendered context.

**Comment by dakur** [comment]
Still do not understand, why it can not be used in different contexts, but thanks for exception at least. :+1:

**Comment by dg** [comment]
It could be used in different contexts (before this commit). Escaping is done directly by `$control->render()` and it is up to it how to escape output.
