### ISSUE TITLE
BC because of added typehints

### ISSUE THREAD

**Issue by mikoczy** [nette/latte#235]
Version: 2.9.0

### Bug Description
This version introduced some breaking changes because of the improved typehints.
In Strict.php, a return type (: void) was added to the __set method. When used with kdyby/strict-objects, an error is raised in the Scream trait on php 7.1.

### Steps To Reproduce
PHP version 7.1
kdyby/translation ^3.0
Kdyby installs the StrictObjects library, which is not compatible with these changes (https://github.com/Kdyby/StrictObjects/blob/v2.0.0/src/Scream.php the return type is not there, and on PHP 7.1 it throws an error).

**Comment by dg** [comment]
It was solved 3 years ago, it isnt? https://github.com/Kdyby/StrictObjects/pull/5

**Comment by lulco** [comment]
Yes, there was [PR](https://github.com/Kdyby/StrictObjects/pull/6) and it is merged to master, but there is no release with those changes.
https://github.com/Kdyby/StrictObjects/compare/v2.0.0...HEAD

Also the changes required php ^7.2, so on machine with php 7.1 will not be installed and will raise error. 

```
Compile Error
Declaration of Kdyby\StrictObjects\Scream::__set(string $name, $value) must be compatible with Latte\Macros\MacroSet::__set(string $name, $value): void
```

**Comment by dg** [comment]
If is this related to the package Kdyby/Translation, the only changed you need is to remove 

```
use \Kdyby\StrictObjects\Scream;
```

from file `TranslateMacros.php`. 

Please send PR and ask to release patch version.
