### ISSUE TITLE
2.9.0 breaks Nittro macros

### ISSUE THREAD

**Issue by jahudka** [nette/latte#236]
Version: 2.9.0

### Bug Description
As of Latte v2.9.0 the [Nittro](https://github.com/nittro/nittro) macros are broken because they contain an invalid character. That character being the dot (`.`).

### Steps To Reproduce
1. Nette skeleton
2. `composer require nittro/nette-bridges`
3. Put `{snippet.id content}` in any Latte template
4. Navigate to the page using that template in the browser

### Expected Behavior
I expected this to work the same as pre-2.9.0.

### Possible Solution
Allow the dot (`.`) in the tag name.

I'm sorry, I'm not very up-to-date with what's new in Nette these days, if there's a perfectly good reason to prohibit dots in Latte tag names I'll work around this somehow (if that's the case, is there another character we can use as a separator in tag names?).

**Comment by dg** [comment]
There is no reason to disable the dot, fixed.

**Comment by jahudka** [comment]
thanks!
