### ISSUE TITLE
BC {snippetArea}

### ISSUE THREAD

**Issue by ikeblaster** [nette/latte#240]
Version: 2.9.0

### Bug Description
`{snippetArea}` without arguments now throws exception `Missing arguments in {snippetArea} in file.latte:10`

### Steps To Reproduce

Compile latte template with following:

```
{snippetArea}
    ...
{/snippetArea}
```

### Possible Solution

https://github.com/nette/latte/blob/c89c46a1da235a38ff87ca477bb3723ce1c4bd27/src/Latte/Macros/BlockMacros.php#L462

Change to:
```
$node->validate(null);
```

**Comment by dg** [comment]
I'm joining @matej21 here.

**Comment by dg** [comment]
What is snippetArea without parameters used for?

**Comment by ikeblaster** [comment]
@dg We used it to solve `Dynamic snippets are allowed only inside static snippet/snippetArea`.

Of course we can use `{snippetArea xyz}`, it works without any problems (and we have done that in our code). But it's still a minor BC issue.

---

More detailed example - not particularly elegant, but it worked for the desired result (redrawing individual controls in AJAX calls). If there is a better solution (which would cover all our needs), we haven't found it yet.

_blocks.latte
```
{define form $formName}
	{snippetArea}
		<form n:name="$formName" class="form-layout">
			<div n:foreach="$form->getControls() as $name => $input"
					n:snippet="$input->htmlId">

				{* custom controls rendering *}
			</div>
		</form>
	{/snippetArea}
{/define}
```

edit.latte
```
{import '_blocks.latte'}

{snippetArea exampleForm}
	{include form exampleForm}
{/snippetArea}
```

**Comment by dg** [comment]
fixed

**Comment by dg** [comment]
Btw, I also removed exception ''Dynamic snippets are allowed only inside static snippet/snippetArea.' in 2.9-dev https://github.com/nette/latte/commit/77d44987c6a109c1645120caa6fbd8760ea11bd7 according to this issue #134. @matej21 is it safe?

**Comment by matej21** [comment]
@dg i think, you won't get any runtime error, so it might be harder to understand why it doesn't work.

**Comment by dg** [comment]
I don't understand snippets at all (No longer) :-)  So have I remove (https://github.com/nette/latte/issues/134#issuecomment-244609405) or keep the check?

**Comment by matej21** [comment]
@dg imho the check is not needed anymore for dynamic snippets to work, but it might be a useful hint for developer. The runtime check/hint could be implemented [in snippet driver when renderingSnippets is false](https://github.com/nette/latte/blob/fec7bd4a393e95e9521c7a1b595ec084eea9a4f8/src/Latte/Runtime/SnippetDriver.php#L47)

**Comment by dg** [comment]
Like this? 1e22713e5fddcedcfdcb7fa4e2684f718bf6571d

**Comment by matej21** [comment]
@dg sth like this https://github.com/matej21/nette-latte/commit/1d2796bc06ee4cd1f4f92aaef6d0a4d6927556a4

**Comment by dg** [comment]
Thanks
