### ISSUE TITLE
BC break in continueIf

### ISSUE THREAD

**Issue by jakubvojacek** [nette/latte#241]
Version: 2.9.0

### Bug Description
`continueIf` inside loop inside if condition throws `Tag {continueIf} is unexpected here in ...`

### Steps To Reproduce
```
{foreach $menus as $menu}
                {if 0}
                    {continueIf true}
                {/if}
            {/foreach}
```

### Expected Behavior
While the usage of continueIf inside another condition might seen a bit weird, this used to work (prior to upgrading to 2.9)

**Comment by dg** [comment]
Duplicate #239
