### ISSUE TITLE
Syntax bug

### ISSUE THREAD

**Issue by Tomix3D** [nette/latte#242]
Version: 2.9.0

### Bug Description
It's unable to use {} in snippet. 
`n:snippet="item-{$id}"`

Getting `syntax error, unexpected '{'`

**Comment by dg** [comment]
It works for me, I am not able to simulate the issue.

**Comment by Tomix3D** [comment]
I don't know how to simulate that issue but I'm using `contributte/datagrid` and after updating latte to 2.9 [this line](https://github.com/contributte/datagrid/blob/master/src/templates/datagrid.latte#L280) is not compiled correctly into latte php class.

`<tr data-id="{$row->getId()}" n:snippet="item-{$row->getId()}" n:attr="$row->getControl()->attrs">`

It generates this line `echo ' id="' . htmlspecialchars($this->global->snippetDriver->getHtmlId($__nm = item-{$row->getId()})) . '"';` Quotation marks are missing for `$__nm`.

**Comment by dg** [comment]
so you probably don't have 2.9.0 but some dev version.

**Comment by Tomix3D** [comment]
Oh, you are right. I was using dev version. My mistake. 

Thank you.
