### ISSUE TITLE
Notice when used n:ifcontent and n:snippet

### ISSUE THREAD

**Issue by janfejtek** [nette/latte#243]
Version: 2.9.0

### Bug Description
When used n:ifcontent and n:snippet on a same element, notice is raised: Undefined variable: __loc

### Steps To Reproduce
`<div n:ifcontent n:snippet="test"></div>`

### Expected Behavior
Throw exception that makes sense or do not create notice.

### Possible Solution
- throw exception with invalid tag usage, something like "do not use ifcontent and snippet on same element as it might produce unexpected behavior"
OR
- add isset check

**Comment by dg** [comment]
Can you check 2.9-dev?

**Comment by janfejtek** [comment]
Notice is different - Undefined variable: __ifc

**Comment by dg** [comment]
fixed
