### ISSUE TITLE
Automatic removing trailing space while writing element

### ISSUE THREAD

**Issue by romankolacek** [nette/latte#246]
In last days there is problem with automatic removing of spaces in latte files. Eg. when user write "<div class" then the space after div is removed and result is "<divclass". It happened automatically. The space is also automatically deleted when user write "<div " and waits a little bit, then there is only "<div" without space.

In phpstorm I tried to disable removing trailing spaces or disable autosaving to prevent checking code, also I tried edit line to trim_trailing_whitespace = false in .editorconfig or disable EditorConfig plugin...but nothing helped.
I did downgrade to 1.0.2 and 1.0.1, again without success.

This problem is only in latte files, in html it is ok.

The space is not autoremoved when I disable Latte plugin so it seems to be problem in this plugin.

**Comment by dg** [comment]
Please write it here https://github.com/nette-intellij/intellij-latte/issues
