### ISSUE TITLE
combination of n:snippet and n:foreach

### ISSUE THREAD

**Issue by chemix** [nette/latte#25]
Now I know that this combination is not working, but is it possible call some excaption? because on the first show no error was called, but after click on button and send some flash message I get something like this "exception 'ErrorException' with message 'Undefined variable: flash'..."

```
<div n:snippet="flashes" n:foreach="$flashes as $flash" class="flash {$flash->type}">{$flash->message}</div>
```

**Comment by paveljanda** [comment]
+1111

**Comment by chemix** [comment]
❤️
