### ISSUE TITLE
Unable to render component in HTML attribute

### ISSUE THREAD

**Issue by dakur** [nette/latte#250]
Version: 2.9.2

### Bug Description
I am not able to render component into HTML attribute, it fails with `Tag {control} must be used in HTML text.`

### Steps To Reproduce
- create a component
- render it with `control` macro into HTML attribute, e.g.: `<html lang="{control languageCode}">`

### Expected Behavior
`<html lang="cs">`

### Possible Solution
Allow it.

### Workaround
```
{capture $languageCode}{control languageCode}{/capture}
<html lang="{$languageCode}">
```
works, but…

**Comment by dg** [comment]
Related to #232
