### ISSUE TITLE
[BUG] {define} block leaves an empty line when rendered

### ISSUE THREAD

**Issue by Ciki** [nette/latte#251]
Version: 2.9.2

### Bug Description
the {define} block now leaves an empty line when rendered, causing eg. XML file being rendered with latte as invalid.

### Steps To Reproduce
```
{define testBlockLeavesEmptyLine}
  blockContent
{/define}
<?xml version="1.0" encoding="Windows-1250"?>
```
it renders first line empty

### Expected Behavior
the {define} block should not be rendered as an empty line

**Comment by dg** [comment]
fixed

**Comment by Ciki** [comment]
thank you!
