### ISSUE TITLE
Filter |stripHtml is not functional in latest version

### ISSUE THREAD

**Issue by Lumeriol** [nette/latte#252]
Version: 2.10

### Bug Description
With new version of Latte there is a bug with filter stripHtml - when used, it show large stack trace in page instead of show classic Tracy with error, and exception file is created.

Fatal error:
Uncaught TypeError: is_file(): Argument #1 ($filename) must be of type string, null given in ...\vendor\tracy\tracy\src\Bridges\Nette\Bridge.php:73\n
Stack trace:\n
0 ...\vendor\tracy\tracy\src\Bridges\Nette\Bridge.php(73): is_file(NULL)\n
1 ...\vendor\tracy\tracy\src\Tracy\BlueScreen\BlueScreen.php(199): Tracy\Bridges\Nette\Bridge::renderLatteUnknownMacro(Object(Latte\CompileException))\n
2 ...\vendor\tracy\tracy\src\Tracy\BlueScreen\BlueScreen.php(156): Tracy\BlueScreen->renderActions(Object(Latte\CompileException))\n
3 ...\vendor\tracy\tracy\src\Tracy\BlueScreen\BlueScreen.php(100): Tracy\BlueScreen->renderTemplate(Object(Latte\CompileException), 'C:\\localhost\\we...')\n
4 ...\vendor\tracy\tracy\src\Tracy\Debugger\Debugger.php(327): Tracy\BlueScreen->render(Object(Latte\CompileException))\n
5 ...\vendor\tracy\tracy\src\Tracy\Debugger\Debugger.php(206): Tracy\Debugger::exceptionHandler(Object(Latte\CompileException))\n
6 [internal function]: Tracy\Debugger::Tracy\{closure}(Object(Latte\CompileException))\n
7 {main}\n

### Steps To Reproduce

`{='<p>one &lt; two</p>'|stripHtml}` or standard `{$foo|stripHtml}`
Tested on PHP 8.0.1 and latest versions of Nette packages.

### Expected Behavior
Same behavior as in version 2.9

**Comment by sasule** [comment]
I can confirm same behaviour with this config:
PHP 7.4.4, PHP8.0.1
Tracy: 2.8.2
Latte: 2.10.0


I've investigated a litte bit but if you patch argument of is_file() function and so on, you will get CompileException with information about wrong context "TEXT" (but expected "html", "xthml" and so on).

So I think it's somehow related to Tracy also.

**Comment by dg** [comment]
Fixed

**Comment by kuty** [comment]
when the fix will be released please?

**Comment by dg** [comment]
Released in 2.10.1
