### ISSUE TITLE
Serialization not possible anymore

### ISSUE THREAD

**Issue by prkwcz** [nette/latte#257]
## Version: 2.10.1
Most probably caused by commit 69e55753707634f05fae0cc1c66daa68f5bc1d86

### Bug Description
Serialising the class is no longer possible. This is occasionally necessary for caching objects.
Error Message: *Serialization of 'Closure' is not allowed*

### Steps To Reproduce
```
$latte = new Latte\Engine;
serialize($latte);
```

### Expected Behavior
Up to this version, serialisation was possible without any problems

**Comment by dg** [comment]
Unfortunately, this cannot be fixed.
