### ISSUE TITLE
Short named arguments syntax fails with key wrapped in apostrophes or quotation marks

### ISSUE THREAD

**Issue by mabar** [nette/latte#261]
Version: 2.10.2

### Bug Description

Apostrophes and quotation marks are not accepted by keys in `[key: value]` syntax

With `=>` were all of these possible:
- `{link paginate!, page => 1}`
- `{link paginate!, 'page' => 1}`
- `{link paginate!, "page" => 1}`

With `:`:
- `{link paginate!, page: 1}` works properly
- `{link paginate!, 'page': 1}` generates `$this->global->uiControl->link("paginate!", ['page': 1])` which results into `\ParseError`

### Expected Behavior

Throw exception that apostrophes and quotation marks are not supported anymore or generate correct code.

**Comment by dg** [comment]
That syntax is based on PHP 8 named arguments syntax, where you also cannot use quotation marks. https://3v4l.org/T5qlK

**Comment by mabar** [comment]
Yup, but the parse error is surprising when you want to migrate to new syntax by simply replacing ` =>` with `:`
Also latte supports that syntax above scope of what php 8 does (in arrays), so I didn't expected it to act differently than previous syntax to match the php behavior.
It's absolutely okay and imho prefferred to support only syntax without quotes, but the current error message can be (and was for me) confusing.

**Comment by dg** [comment]
In Latte 3 it already reports a message at compile time that ':' is unexpected.
