### ISSUE TITLE
Rendering fails with "Error Number: 2" when template is not yet cached

### ISSUE THREAD

**Issue by TheRealMrG** [nette/latte#264]
Version: 2.10.3
PHP Version: 8.0.2

### Bug Description
Rendering a template that does not yet have an entry in the cache causes the script to stop with the following message:
`Error Number: 2
Error: filemtime(): stat failed for [filename].php
File: [path]\vendor\latte\latte\src\Latte\Engine.php
Line: 257`

### Steps To Reproduce
1. Create a new template or clear the cache. 
2. Start a script that renders a template from a file (i.e. using FileLoader)

### Expected Behavior
Template to display and cache file to be created without errors.

### Possible Solution
Line 257 in Engine.php is as follows:
`return $this->autoRefresh && $this->getLoader()->isExpired($name, (int) @filemtime($file)); // @ - file may not exist`
The filemtime() call is prepended with an @ to prevent errors. However, the @ error control operator has changed behaviour in PHP 8 and will not suppress this error. I have tested the following fix locally:
` $filetime = (file_exists($file)) ? (int) filemtime($file) : 0;
return $this->autoRefresh && $this->getLoader()->isExpired($name, $filetime);`

**Comment by dg** [comment]
You're using some custom error handler that throws this error message. PHP does not throw errors in form `Error Number: 2 Error: ...`

**Comment by TheRealMrG** [comment]
> You're using some custom error handler that throws this error message. PHP does not throw errors in form `Error Number: 2 Error: ...`

Correct, my custom error handler is formatting the error slightly differently. Apologies, I should have flagged that.

**Comment by TheRealMrG** [comment]
> You're using some custom error handler that throws this error message. PHP does not throw errors in form `Error Number: 2 Error: ...`

Apologies, just realised my custom error handler was seeing the non-zero response as a terminal error and killing the script. Sorry for the timewasting.
