### ISSUE TITLE
Incorrect behavior of n:iterateWhile (differs from "non n-tag" version)

### ISSUE THREAD

**Issue by khorsky** [nette/latte#273]
Version: 2.10.3

### Bug Description
When using n-tag version of **iterateWhile**, generated output does not equal to non-tagged version (first item is skipped?).

### Steps To Reproduce
https://fiddle.nette.org/latte/#a8012a3587 (broken n-tag version) vs https://fiddle.nette.org/latte/#f9a61fe9b9 (working non-tagged version)

### Expected Behavior
Generated result is same for both **iterateWhile** and **n:iterateWhile** versions

### Possible Solution
By comparing generated templates, it looks like the condition is written to beginning of the foreach cycle when using n-tag version...

**Comment by dg** [comment]
Because it is the same as 

```latte
{iterateWhile $item['parent'] === $iterator->nextValue['parent']}
        <li>
            {$item['title']}
        </li>
{/iterateWhile}
```
