### ISSUE TITLE
Bridge to tracy require nette/utils and it is not presented in composer requirements

### ISSUE THREAD

**Issue by Kubina1232** [nette/latte#274]
Version: master

### Bug Description
When using latte without nette framework it is not possible to use bridge to tracy. Framework is using some helpers from nette but nette is not in dependencies in composer.json file.

### Steps To Reproduce
Try to use it without nette framework

### Expected Behavior
Working tracy bar without missing components

### Possible Solution
Add nette/utils to composer requirements

**Comment by dg** [comment]
fixed
