### ISSUE TITLE
Latte throws Latte\CompileException if `'{$var|noescape}'` is used in javascript

### ISSUE THREAD

**Issue by forgie1** [nette/latte#283]
Version: 2.10.9|2.11.0

### Bug Description

Latte throws Latte\CompileException if `'{$var|noescape}'` is used in javascript:
```
Latte\CompileException
Do not place {$something|noescape} inside quotes in JavaScript in ...
```
### Expected Behavior
If |noescape filter is used, variable may be used inside quotes in javascript

**Comment by dg** [comment]
Follow the advice :)

**Comment by forgie1** [comment]
My original example was simplified.
How to follow the advice in this case:

`someJsCall(“abc”, “id-{$id|noescape}”`

I'm looking for strait forvard solution, not workaround.

This is how lattle handled |noescape filter in JS up to version 2.10.8 included.

**Comment by dg** [comment]
Use this `someJsCall("abc", "id-" + {$id|noescape})`

**Comment by namo-R** [comment]
but, how can I get there text with html (for example), that why noescape :(

**Comment by forgie1** [comment]
rendered HTML with JS does not look "nice" than:
 `someJsCall("abc", "id-" + "websiteId")`. 
 In some cases much more + signs are used, eg: 
 `"id-" + "myId" + "/" + "conversionId"`
 The way it was before result JS in HTML was "prettier" :) And was really strait forward to use it in latte thanx to '|noescape'.

It is my personal view, maybe I'm alone seeing it this way...

**Comment by forgie1** [comment]
Thank you, this is nice :)

**Comment by dg** [comment]
Just to explain why Latte throws out this exception. Because you tried to create a security hole.

If I put this string into a variable `$id = '", (evilcode)()'`, this will cause code execution:
```latte
someJsCall("abc", "id-{$id|noescape}")
```
```js
someJsCall("abc", "id-", (evilcode)())
```

**Comment by forgie1** [comment]
Thank you 👍 
Yes, I understand. It is written also in latte doc.

Using latte macro to print expression you suggested [here ](https://github.com/nette/latte/issues/283#issuecomment-1048906567) is definitely better solution.
