### ISSUE TITLE
{import} static method call is compiled as file name

### ISSUE THREAD

**Issue by MartkCz** [nette/latte#284]
Version: [2.11.0](https://github.com/nette/latte/releases/tag/v2.11.0)

### Steps To Reproduce
```html
{import App\UI\Form\FormBlocks::getFile()}
```

throws

`Missing template file 'absolute-path/App/UI/Form/FormBlocks::getFile()'`

this is ok `{import App\UI\Form\FormBlocks::getFile() . ''}`

### Expected Behavior
Same behavior as variable

**Comment by dg** [comment]
It can be solved like this: `{import (App\UI\Form\FormBlocks::getFile())}`.

In version 2.x I won't change the behaviour and in version 3.0 it is solved.
