### ISSUE TITLE
Please add an early exit feature for latte templates

### ISSUE THREAD

**Issue by BernhardBaumrock** [nette/latte#287]
- Explain your intentions

As explained in this forum question I'd need an early exit feature in latte templates: https://forum.nette.org/en/35172-early-exit-in-latte-template-file

This follows the guard clause instead of if/else-nesting, see https://www.youtube.com/watch?v=EumXak7TyQ0 why this can be good for reducing code complexity and making it easier to read and maintain.

- It's up to you to make a strong case to convince the project's developers of the merits of this feature

I've built a page builder for the ProcessWire CMS that looks like this:

![img](https://i.imgur.com/Zf8sTia.png)

These content blocks consist of a controller file and a view file. The controller file is PHP (eg Gallery.php), the view file is LATTE (eg Gallery.latte).

A simple view file could look like this:

```latte
<h1>{$block->headline}</h1>
<div n:inner-foreach="$block->images() as $img">
   ...
</div>
```

Now what I'd like to do is to only render the view file if certain conditions are met. In this example it would be great to only render the gallery view file if the block has at least one uploaded image.

```latte
{returnif !$block->images()->count()}
<h1>{$block->headline}</h1>
<div n:inner-foreach="$block->images() as $img">
   ...
</div>
```

Without this feature I need to wrap my view markup in an if condition:

```latte
{if $block->images()->count()}
  <h1>{$block->headline}</h1>
  <div n:inner-foreach="$block->images() as $img">
     ...
  </div>
{/if}
```

Thx for considering :)

**Comment by dg** [comment]
I would probably use `skipIf` rather than `returnIf`…

**Comment by BernhardBaumrock** [comment]
@MartinMystikJonas good point, didn't think of that. IMHO it's ugly, so it's partly just a personal preference :) But there are often cases where early exists are a lot cleaner than if/else/and/or...

```latte
{skipIf !$block->images()->count()}
{skipIf $block->settings->foo}
{skipIf $block->settings->bar AND $block->title == 'bar'}
<h1>{$block->headline}</h1>
<div n:inner-foreach="$block->images() as $img">
   ...
</div>
```

**Comment by dakur** [comment]
@dg I would probably expect `skipIf` to be a pair tag that bounds *what* should be skipped. Maybe `stopIf` would be an option?

**Comment by BernhardBaumrock** [comment]
@dakur that's exactly what skipIf should NOT be. As you describe it {skipIf} would just be the opposite of {if} and that's not what I want. I'm talking of a new concept that skips rendering of the whole latte file if a condition is met. So {skipIf} would not have any closing tag by design.

**Comment by dakur** [comment]
@BernhardBaumrock I know, I understood your proposal. I'm discussing the word to be used and its sense – how it's read and understood in the code.

Word "skip" in my opinion implies that it will be further defined (inside of the tag) what should be skipped, whereas "return"/"break"/"stop" clearly says that the code execution stops in that place for whole file.

Example – if I see this code:

```latte
{returnIf !$block->images()->count()}
<h1>{$block->headline}</h1>
<div n:inner-foreach="$block->images() as $img">
   ...
</div>
```

I clearly understand that if condition is not met, whole template ends rendering. While if I see

```latte
{skipIf !$block->images()->count()}
<h1>{$block->headline}</h1>
<div n:inner-foreach="$block->images() as $img">
   ...
</div>
```

a question arises: "wait, but what should be skipped?"

At least that's my perception of it.

**Comment by BernhardBaumrock** [comment]
Ah, thx @dakur good point. I think that will also fit better into the principle of latte being very close to plain PHP and not a different language.

**Comment by dg** [comment]
For me it was about reusing existing tag in a new context https://latte.nette.org/en/tags#toc-continueif-skipif-breakif

**Comment by dakur** [comment]
In that context, `skipIf` seems like a solution for a particular problem – being able to `continueIf` while preserving the counter. But still, the loop gives a sense of the context – what is being skipped. When the context is whole template file, I think it's not so obvious. I can see more similarity to `breakIf` than to `skipIf`.

But it's just wording, the point is the functionality of course, words can be changed any later. :-)

**Comment by milo** [comment]
@dg What about somehow extend the ifContent macro? To be able hide parents/siblings?

**Comment by dg** [comment]
I see it exactly the opposite :-) The term `return` doesn't mean anything to me in the context of templates. What to return? Where to return to? On the contrary, it is common to use skip to … ehm … skip https://phpunit.readthedocs.io/en/9.5/incomplete-and-skipped-tests.html#skipping-tests

**Comment by dakur** [comment]
In tests, you skip whole test, you don't say "skip" from the middle of the test. But it's true that Bernhard posted a use-case with skip at the beginning, not in the middle, so I give up. 🙂

**Comment by dg** [comment]
I understood it from the beginning as early exit, i.e. ending on the first line.

Maybe we could also use `endIf`.

**Comment by dg** [comment]
I'm gonna try to do a poll on this.

**Comment by MartinMystikJonas** [comment]
exitIf - similar to exit()
skipIf - already used in different context
endIf - can be confused with {/if}
returnIf - IMHO best but not exactly right either

What about terminateIf?

**Comment by pavelmlejnek** [comment]
Few quick thoughts:

abortIf
breakIf
cancelIf
discontinueIf
haltIf
endIf



Dne čt 21. dub 2022 18:19 uživatel Martin Mystik Jonáš <
***@***.***> napsal:

**Comment by vojtech-dobes** [comment]
finishIf

**Comment by dg** [comment]
The goal was to reach a consensus :-)

**Comment by milo** [comment]
What about the opposite meaning?
```latte
{renderIf $block->images()->count()}

<h1>{$block->headline}</h1>
<div n:inner-foreach="$block->images() as $img">
   ...
</div>
```

**Comment by dg** [comment]
The `quitIf`  and `leaveIf` hasn't come up yet :)

**Comment by BernhardBaumrock** [comment]
Ok I didn't know back in April, but now I know that my suggested priciple does actually have a name and is called "guard clause". A guard clause is here to reduce complexity and make code more readable, which is exactly why I proposed the feature. Read here: https://deviq.com/design-patterns/guard-clause or see here:

https://www.youtube.com/watch?v=EumXak7TyQ0

**Comment by badpenguin** [comment]
Well i've always used just php return since 2.4 but now with 2.* it force me to use "return []"

**Comment by BernhardBaumrock** [comment]
any news on this @dg ?

**Comment by BernhardBaumrock** [comment]
@badpenguin what do you mean? I don't understand. On my end there seems to be no easy way out of a rendered latte file once rendering has started...

**Comment by badpenguin** [comment]
> 

I just do ```<?php return; ?>```

**Comment by BernhardBaumrock** [comment]
@badpenguin we are talking about LATTE files, not PHP files ;) That's exactly what I'm requesting. Make a feature that is extremely easy to do in PHP also available to LATTE.

**Comment by BernhardBaumrock** [comment]
@dg related to this discussion there's also another request/question:

In the PW forum someone came up with a hacky "includeIF" solution:

```
{include $foo = 'bar' ? "test.latte" : "blank.latte"}
```

The problem is that you need to define a second template otherwise latte throws an error.

It would be nice to have something like this:

```
{include $foo = 'bar' ? 'somefile.latte'}
```

**Comment by dg** [comment]
I find this more understandable:
```latte
{if $foo == 'bar'}{include 'somefile.latte'}{/if}
```

**Comment by BernhardBaumrock** [comment]
Hey @dg unfortunately I'm not able to use this new feature :( Any idea what I could be doing wrong?

<img width="607" alt="image" src="https://github.com/nette/latte/assets/8488586/728504b8-4519-48c5-98d8-074ea20dd373">

I tested with `{exitIf $page->template != 'releasepage'}` initially but same error.

**Comment by dg** [comment]
fixed

**Comment by BernhardBaumrock** [comment]
Great, thx @dg !
