### ISSUE TITLE
Latte\CompileException Thrown exception 'Attempt to read undeclared property Latte\Compiler\Nodes\Php\ModifierNode::$escape.' (in '.../Basic/default.latte')

### ISSUE THREAD

**Issue by petrparolek** [nette/latte#290]
Version: 3.0.0-beta2

### Bug Description
[exception--2022-04-30--12-42--875282c3b8.zip](https://github.com/nette/latte/files/8596713/exception--2022-04-30--12-42--875282c3b8.zip)

### Steps To Reproduce

Use datagrid skeleton from https://github.com/contributte/datagrid-skeleton/pull/68 with these composer packages:

contributte/application	v0.5.1
dibi/dibi	v4.2.6
latte/latte	v3.0.0-beta2
nette/application	v3.1.x-dev #5443
nette/bootstrap	v3.1.2
nette/caching	v3.1.2
nette/component-model	v3.0.2
nette/di	v3.0.13
nette/finder	v2.5.3
nette/forms	v3.1.x-dev #c2f1
nette/http	v3.1.6
nette/neon	v3.3.3
nette/php-generator	v4.0.1
nette/robot-loader	v3.4.1
nette/routing	v3.0.3
nette/schema	v1.2.2
nette/security	v3.1.5
nette/utils	v3.2.7
symfony/polyfill-ctype	v1.25.0
symfony/polyfill-intl-grapheme	v1.25.0
symfony/polyfill-intl-normalizer	v1.25.0
symfony/polyfill-mbstring	v1.25.0
symfony/property-access	v6.0.8
symfony/property-info	v6.0.7
symfony/string	v6.0.8
tracy/tracy	v2.9.2
ublaboo/datagrid	dev-master #e7b0

ref: https://github.com/contributte/datagrid/pull/1027

**Comment by dg** [comment]
Use Latte dev

**Comment by petrparolek** [comment]
thx fixed
