### ISSUE TITLE
Call to undefined method Nette\Bridges\ApplicationLatte\DefaultTemplate::addFilterLoader()

### ISSUE THREAD

**Issue by devmal** [nette/latte#294]
Version: v2.11.3

### Bug Description
In this version Engine::addFilter(null, ...) is deprecated, use addFilterLoader().
But Tracy in Nette shows:
Call to undefined method [Nette\Bridges\ApplicationLatte\DefaultTemplate::addFilterLoader]

### Steps To Reproduce
$this->template->addFilterLoader([new Filters, 'loader']);

**Comment by dg** [comment]
Use `$this->template->getLatte()->addFilterLoader([new Filters, 'loader']);`

**Comment by devmal** [comment]
It works fine. Thank you.
