### ISSUE TITLE
Compile literals

### ISSUE THREAD

**Issue by pixobit** [nette/latte#295]
- Would it be possible to evaluate all the literal calls like translation of constants, or including another file into the template, etc?

- The reason for this, is to further improve performance. This could be a chance to make it actually faster than pure php, with the help of compilation

**Comment by mabar** [comment]
> The reason for this, is to further improve performance.

Do you have a proof for that? Afaik such change is not noticable at all.

Even constant values are not trully immutable (let's use PHP_VERSION_ID for example), counting with their immutability may lead to bugs.

**Comment by pixobit** [comment]
Don't need proof for something like that. It's obvious, and relative to the one using the engine, because our implementations might differ. Let's say for example I implement a very poor translation engine (it can be fast, it's still a bottleneck... just trying to emphasize), which I'm using in latte to translate all the keys, and I'm having over 100 of these on one page. In this case the compiled version would still be slow, since all the translation call would slow down the application.

In this case {_'example_text'} won't change outside of a language key, or if it does, we can always recompile it somehow, while {_$dynamicKey} is a variable, so we need to translate it runtime. I belive compiling the translation could enhance performance in this scenario. And while we could argue that making the translation more performant is the right solution, the compiler could reach higher performance, even if the translation is efficient.

I believe this should be a tool developers can control somehow, since latte doesn't know how to differentiate languages by itself for example. But this could be easily solved by being able to define compile groups, or something to differentiate between them.

**Comment by milo** [comment]
Not proof but some measurement would be great. Code complexity is the cost. But for milliseconds or nanoseconds?

**Comment by pixobit** [comment]
Alright, I will make some measurements after I set up the templating engine, and come back to this

**Comment by mabar** [comment]
Opcache usually achieves way better micro optimizations than we can do directly in php. Also 100 cases are really small amount. If you will measure any difference, it will probably be with 100k or even 1M+ cases. That's just not worth the potential bugs.

Values of some constants may be dynamic. Even "static" files may change any time, especially when an virtual filesystem is used.

Come back to this, once you have setup opcache without re-checking files in production, imported all functions to prevent useless lookup to current and global namespace, bootstraped application before request, used async for all files and sql requests, optimized queries to use indexes, ...
Ton of way more efficient and less buggy optimizations exists, inlining some static values is really smallest of all microoptimizations. Trust me with this, I am trying to get responses in units of miliseconds for years :)

**Comment by pixobit** [comment]
While I agree with what you said, you seem to ignore the fact the you're answering the unknown. Maybe that's because you've misunderstood me.
The reason it's unknown, is because you don't know what kind of functions does the user have. There could be countless cases  where the function is deailing with constants. To mention some of them: translation, converting relative urls, including partial files, using system configuration values...
I do agree though that opcache would do a lot more here, but I still thought it might be worth to look into, since I like to maximize the performance, the same way some developers try to squeeze out every byte of their js libraries.
But if this would bring in potential bugs, then definitely not worth it.

**Comment by milo** [comment]
@pixobit You brought a good idea, don't be discouraged. Although I can't speak for the Latte author, I think that speed tests and specifications of the exact use cases are crucial.

**Comment by dg** [comment]
Yeah, something like that can be done in Latte v3.

**Comment by pixobit** [comment]
> Yeah, something like that can be done in Latte v3.

That sounds great! Really love the project, and looking forward for v3.

**Comment by pixobit** [comment]
I guess in that case you can close this issue then. Or if you want to leave it open, I might come back with a banchmark when I manage to set things up, but it might take a while

**Comment by pixobit** [comment]
While I still haven't done any benchmarks, I just wanted to share how great this literals caching is in v3.
I haven't thought about this originally, but having this feature in v3 let me overwrite the TranslationExtension, and synchronize the translation keys for my dictionary on compilation level. I could've never done this without this feature, since it's a pretty expensive process. Now I don't need to keep track of my translation keys, since latte does that for me.

**Comment by dg** [comment]
Static text translations can already be evaluated during compilation https://latte.nette.org/en/develop#toc-translatorextension

**Comment by pixobit** [comment]
Yes, I'm already using it for translations, asset loading, and routing. 
I really love the new version :) v3 is a huge improvement over v2.
I guess you can close this thread if you want to.
