### ISSUE TITLE
Latte 3 does not allow {define} inside {embed}

### ISSUE THREAD

**Issue by JanTvrdik** [nette/latte#299]
Version: 3.0.0

The following template used to work in Latte 2.x, but in Latte 3 result in error "Unexpected content inside {embed} tags". Using `{block}` instead of `{define}` seems to work.

https://github.com/nette/latte/blob/v3.0.0/src/Latte/Essential/Nodes/EmbedNode.php#L59

~~~latte
{define layout}
	<div class="layout-content">
		{include content}
	</div>
{/define}

{embed layout}
	{define content}
		Hello World
	{/define}
{/embed}
~~~

**Comment by dg** [comment]
I think this is correct, inside the embed should not be define.
