### ISSUE TITLE
Missing what's `$control` in docs

### ISSUE THREAD

**Issue by simPod** [nette/latte#300]
I'm trying to upgrade to Latte 3 from v2

This is what I used to do

```php
    /** @param array<string, mixed> $parameters */
    public function createAndRenderToString(string $name, array $parameters): string
    {
        $template = $this->templateFactory->createTemplate();

        $latte = $this->latteFactory->create();
        UIMacros::install($latte->getCompiler());
        $latte->addProvider('uiControl', $this->linkGenerator);

        return $latte->renderToString($name, array_merge($template->getParameters(), $parameters));
    }
}
```

But `$latte->getCompiler()` does no exists on v3

I found docs https://latte.nette.org/cs/cookbook/migration-from-latte2#toc-aktualizace-doplnku

And it says to change 

```diff
- Nette\Bridges\ApplicationLatte\UIMacros::install($latte->getCompiler());
+ $latte->addExtension(new Nette\Bridges\ApplicationLatte\UIExtension($control));
```

Where do I get the `$control`. What is it? It is not in the docs.

------

I just need to render a template with some params into html string. I have no $control.

**Comment by dg** [comment]
You can pass `null`.

**Comment by simPod** [comment]
Did the trick. Thanks
