### ISSUE TITLE
Not possible define tags attributes dynamically with if anymore

### ISSUE THREAD

**Issue by Kubina1232** [nette/latte#308]
Version: 3.0.x-dev

### Bug Description
After update to newest version of latte it is no longer possible define HTML tags atributes via if.

### Steps To Reproduce
Check attachement code

### Expected Behavior
Work as before -> no problem, successful compilation

#### BUG message
```
'Unexpected '</div>
   ' (on line 21 at column 18)'
```

Which corresponds to if in this tag

```
<input type="text" class="form-control"
                           name="username" id="username"
                           placeholder="{_"Username"}" required="required"
                           {if ($_ENV['ENVIRONMENT']== 'test')}
                               value="test"
                           {/if}
                           >
```
![image](https://user-images.githubusercontent.com/77285090/175832007-c4ffae10-9564-4996-90b9-f7621f0f3ccf.png)
![image](https://user-images.githubusercontent.com/77285090/175832040-09ce30c4-84b5-43e7-8552-a2bff0c2cfb4.png)

**Comment by dg** [comment]
The problem is somewhere else https://fiddle.nette.org/latte/#ab560f0c17

**Comment by dg** [comment]
@Kubina1232  Did you find out where the problem is?

**Comment by Kubina1232** [comment]
Unfortunately not.
I have rewrote it to use variable. 


Also now I see it is working locally with dev-master #f446 (so maybe so bug in some master build... who knows)
