### ISSUE TITLE
TagParser BC break in 3.0.5

### ISSUE THREAD

**Issue by xificurk** [nette/latte#325]
Version: 3.0.5 RC

### Bug Description
Rename of `TagParser::tryConsumeModifier()` -> `TagParser::tryConsumeSeparatedToken()` is a BC break.

### Steps To Reproduce
Failing build against dev Latte version: https://github.com/nepada/bust-cache/actions/runs/3764912603/jobs/6399842584

### Expected Behavior
Passing buid against latest stable Latte version: https://github.com/nepada/bust-cache/actions/runs/3764912603/jobs/6399842671 

### Possible Solution
Could we keep the old method at least as deprecated alias?

**Comment by dg** [comment]
Fixed. 

I'm gonna name the method `tryConsumeTokenBeforeUnquotedString()`
