### ISSUE TITLE
Some PHP functions used in {do} are namespace\ prefixed in latte cache file, resulting in Error

### ISSUE THREAD

**Issue by forgie1** [nette/latte#327]
Version: 3.0.4

### Bug Description
For example PHP function `unset()` can not be called in {do} macro:

> Error
> Call to undefined function unset(), did you mean reset()?

In Latte Cache file it is prefixed : `namespace\unset($abc)`.

### Steps To Reproduce
{do unset($abc)}

### Expected Behavior
`$abc` is unset.

**Comment by dg** [comment]
I'll find out why this is happening, however to use unset you need to install RawPhpExtension https://latte.nette.org/en/develop#toc-rawphpextension

**Comment by forgie1** [comment]
Thank you
