### ISSUE TITLE
Printing data - when start with space will not output / print the data correctly

### ISSUE THREAD

**Issue by ampmonteiro** [nette/latte#330]
Version: 3.0.5

### Bug Description
when i am printing a variable or a result of function will not output correctly the data or even apply filters, when start with space.

### Steps To Reproduce

```php

<p>{ $var}</p>

<p>{ $var|upper}</p>
```

[lattefield](https://fiddle.nette.org/latte/#6f2eae032b 'click to show')

![image](https://user-images.githubusercontent.com/31895754/219874397-a8253128-6a54-4596-affb-41c5384502b4.png)

### Expected Behavior
Like others template engine or even on php when using short print way, it will display even when start with a space

### Possible Solution
Some how should be trimmed before being processed.

**Comment by mabar** [comment]
This is actually documented behavior https://latte.nette.org/en/syntax#toc-tags

> If the { character is followed by a quote or space, Latte doesn't consider it to be the beginning of a tag, so you can use JavaScript constructs, JSON, or CSS rules in your templates without any problems.
