### ISSUE TITLE
Tag {_} in some cases cannot be used in translations

### ISSUE THREAD

**Issue by janda-quitec** [nette/latte#332]
Version: since 3.0.0

Bug Description:

PHP file:
$this->template->setFile('template.latte');
$this->template->addFilter('translate', [$this->translator, 'translate']);
$this->payload->html = (string)$this->template;

template.latte:
{='Text'|translate}  {* this is possible *}
{_'Text'}                  {* this is NOT possible *}

It throws the Latte\CompileException: Unexpected tag {_}, did you mean {=}?

**Comment by lukaspijak** [comment]
This tag is removed and replaced by `{translate} … {/translate}`

**Comment by dg** [comment]
https://latte.nette.org/en/cookbook/migration-from-latte2#toc-translations
