### ISSUE TITLE
Different compiling of comma and space between strings in n attribute

### ISSUE THREAD

**Issue by mildabre** [nette/latte#333]
Latte 3.0.6

### Bug Description
I have tested how n-attributes handle quoted versus unquoted attribute value. The function should be identical independently on quoting/unquoting of attribute value, but I have found a difference - when is between comma separated strings a space.

Here is a sample of code (better to see it on fiddle - link bellow)

```
<span n:class =class1,class2>case a</span>

<span n:class =class1, class2>case b</span>

<span n:class ="class1,class2">case c</span>

<span n:class ="class1, class2">case d</span>
```

### Steps To Reproduce

Look samples of code with my comments on fiddle latte:

https://fiddle.nette.org/latte/#bed1e173f7

### Expected Behavior

Compiling identical html or the value of attribute is quoted or unquoted - i.e. latte n:class=string1, string2 will compile into class="string1 string2", not class="string1" string2

**Comment by dg** [comment]
Try to see how the browser understands this html:
```html
<span class =class1, class2>case b</span>
```

**Comment by mildabre** [comment]
Yes,

testing of your html code samples in browser and validator shows that browser tolerate html unquoted attributes, but two classes in one unquoted attribute never work correctly.

Back to my issue, the current latte engine 3.0.6 compiles different html for these two latte codes:

<span n:class=class1,class2>

and

<span n:class=class1, class2>

This means that put space between class1 and class2 in latte code changes compiled html. This is for the user tricky behaviour and about correcting it was the issue.

Anyway unquoted html attributes or latte n-attributes are bad idea at all, leading to many unnecessary problems, one of which is this issue. So let be this issue closed.

**Comment by dg** [comment]
If the attribute contains spaces, it must be in quotes. In the browser and in Latte.
