### ISSUE TITLE
Add support for array destructuring in tag {var}

### ISSUE THREAD

**Issue by mildabre** [nette/latte#337]
Hi,

the intended purpose of latte tag {var} is to fill values into variables, while on the other hand the purpose of latte tag {do} is just to execute one line of code.

At the time being unfortunately it is not possible to use destructuring array into variables like this:

```latte
{var
    [$var1, $var2] = match($key){
        'key1' => ['value11', 'value21'],
        'key2' => ['value12', 'value22'],
        'key3' => ['value13', 'value23'],
    }
}
```
This destructuring would be in Latte templates useful, because there are many cases when you need put a type into template and insight the template get more than one variables for example a) text message, b) css class.

Now it is possible to use for this purpose tag {do}:

```latte
{do
    [$var1, $var2] = match($key){
        'key1' => ['value11', 'value21'],
        'key2' => ['value12', 'value22'],
        'key3' => ['value13', 'value23'],
    }
}
```

But it would be better to use for assigning variables tag {var}. Destructuring array into variables is natural way of assigning variables in PHP and shoud be supported by the tag {var}.

**Comment by dg** [comment]
This is very complicated to deal with.
