### ISSUE TITLE
Invalid rendering of dynamic xml tags with namespace

### ISSUE THREAD

**Issue by survik1** [nette/latte#343]
Version: 3.0.6

### Bug Description
XML tags that with constant namespace and dynamic value (`<ns:{$name}></ns:{$name}>`) are rendered incorrectly. I am sharing a snippet that displays error in closing tag, yet our production XML had several cases with completely missing content of the tag (=>unitPrice was missing). Sadly I am not able to simulate the second case in this example but i guess it will be related to shown error. 

Current workaround is to fully qualify name including the namespace inside the variable. 

### Steps To Reproduce
https://fiddle.nette.org/latte/#233601efd1

### Expected Behavior
Closing tag should be rendered as `</inv:homeCurrency>`

**Comment by dg** [comment]
implemented in 3.0.9
