### ISSUE TITLE
Coffee covers text on website

### ISSUE THREAD

**Issue by janopae** [nette/latte#350]
Hi, I'm not sure if this is the right place to post this (pretty much doubt it but I didn't find a better place), but there's a problem with the website https://latte.nette.org/. I can't read the text, because there's coffee on it.

This is how the website looks in my browser (Firefox 119.0): 

<img width="1093" alt="grafik" src="https://github.com/nette/latte/assets/8160319/ef8ba3e6-4576-4a70-9d34-e0cd7a60df08">

Extensions are not the problem, as this happens it private mode, too.

It also stays this way when I zoom in or out.

**Comment by dg** [comment]
Thanks for the notice, fixed
