### ISSUE TITLE
Change the approach for {last} to be more like {else} on {foreach} loops, so that it would not be affected by {skipIf}

### ISSUE THREAD

**Issue by starfishpatkhoo** [nette/latte#375]
Version: 3.0.18

So I'm trying to have a simple index listing of pages.

```php
{foreach $page_list as $slug => $page}
{skipIf ((! $user->is_admin()) && ($page->is_draft()))}
{first}<h1>List of Pages</h1><ul>{/first}
<li><a href={$slug}>{$page->title}</a></li>
{last}</ul>{/last}
{else}
<div class="alert">Oops! No Pages Found!</div>
{/foreach}
```

Now if it so happens that the last page in `$page_list` is a draft, and the user is not an admin, then the `{last}` never gets executed. Note that this also happens if we use `{continueIf}` instead. 

A few observations:

* If `{first}` came before the `{skipIf}` then of course `{first}` would get executed even if everything was skipped - which is expected and correct behaviour.
* If we put `{last}` before the `{skipIf}` then it would work, but if the last page is a "visible" page, then the `<ul>` would appear before the actual link - which is also expected and correct behaviour, even if that's not what we want.

I know this is not really a Latte specific problem - it's the way loops are handled/done in the programming language. One could talk about setting a flag or counter to indicate if there is or isn't any data (and so the `<ul>` needs to be closed). Or maybe rejig the whole thing with more `{if}` statements instead. Or redesign the HTML so we do not depend on `{first}` and `{last}` to handle the `<ul>` tag.

But I'm just wondering if there is an easier, Latte-specific way (with nice tools like `{skipIf}`, `{first}`, `{last}` and `{else}`) to make this sort of thing happen?

I feel that for `{last}`, if we use a similar approach to handling `{else}`, we can execute `{last}` on the last iteration (even if it was `{skipIf}`-ed), as long as there was some data that wasn't `{skipIf}`-ed earlier.

Another approach, or another way to think about it, is to define a `{header}` and `{footer}` (for lack of a better word) that is executed before the first data in the loop (if there is data after any `{skipIf}`), and after the last data in the loop (if there was data). I think such a thing would be very useful for many common scenarios where we need to loop through stuff and display them.

```php
{foreach $page_list as $slug => $page}
{header}<h1>List of Pages</h1><ul>{/header}
{footer}</ul>{/footer}
{skipIf ((! $user->is_admin()) && ($page->is_draft()))}
<li><a href={$slug}>{$page->title}</a></li>
{else}
<div class="alert">Oops! No Pages Found!</div>
{/foreach}
```

Ref #263 points to a similar issue, but affecting `{sep}` instead. I admit I think that is an even more complex problem to solve because one needs to look _AHEAD_ in the loop to decide if there is or isn't another item after this (hence needing a `{sep}`). Maybe that requires an advanced version of `implode()`.

**Comment by starfishpatkhoo** [comment]
Anyway, for anyone who happens on this issue, one way to achieve this is to add a flag (or counter) and not use `{last}`

```php
{var bool $have_data = false}
{foreach $page_list as $slug => $page}
{skipIf ((! $user->is_admin()) && ($page->is_draft()))}
{first}<h1>List of Pages</h1><ul>{/first}
{var bool $have_data = true}
<li><a href={$slug}>{$page->title}</a></li>
{else}
<div class="alert">Oops! No Pages Found!</div>
{/foreach}
{if $have_data}</ul>{/if}
```

Be sure to initialize the flag _OUTSIDE_ the foreach or else you will have an error if everything got `skipIf`-ed.

Another way is to redesign this to be more like the example in official documentation.

```php
<h1>List of Pages</h1><ul>
{foreach $page_list as $slug => $page}
{skipIf ((! $user->is_admin()) && ($page->is_draft()))}
<li><a href={$slug}>{$page->title}</a></li>
{else}
<li>Oops! No Pages Found!</li>
{/foreach}
</ul>
```

But as you can see, the error message is now an entry in the `<ul>` list, and not an error box.

**Comment by dg** [comment]
Opening tags in places where they are not closed (like `<ul>` in `{first}<h1>List of Pages</h1><ul>{/first}`) creates very confusing code, so avoid doing that. A much better solution is the second one. 

To prevent the error message from being output inside the `<ul>` list, use the `{try}` tag:

```php
{try}
	<h1>List of Pages</h1>
	<ul>
	{foreach $page_list as $slug => $page}
		{skipIf ((! $user->is_admin()) && ($page->is_draft()))}
		<li><a href={$slug}>{$page->title}</a></li>
	{else}
		{rollback}
	{/foreach}
	</ul>
{else}
	<div class="alert">Oops! No Pages Found!</div>
{/try}
```

**Comment by dg** [comment]
It's not possible to modify the behavior of `{last}`, precisely due to the lookahead problem you mentioned.
