### ISSUE TITLE
FileLoader::normalizePath doesn't take into consideration phar:// at the beginning of the path

### ISSUE THREAD

**Issue by Marian-Kechlibar** [nette/latte#378]
Version: 3.0.18

### Bug Description
The internal method of the class FileLoader

`protected static function normalizePath(string $path): string`

converts all  forward slashes in the supplied path to backslashes on Windows before returning: 

`return implode(DIRECTORY_SEPARATOR, $res);`

This is correct for normal canonical paths to files, but doesn't work in the very specific case of files loaded from a PHAR archive. 

Their path starts with phar://, such as:

'`phar://C:/xampp/htdocs/kraken-control-tester/kraken-control.phar/app/Module/Basic/Presenters/templates/...'`

and the method normalizePath will convert this blindly into:

'`phar:\\C:\xampp\htdocs\kraken-control-tester\kraken-control.phar\app\Module\Basic\Presenters\templates\....'`

Due to this blind conversion, rendering of Latte templates loaded from PHARs on Windows breaks down.

A one-line solution is to convert the :\\\\ back to correct value:

```
$res_str = implode(DIRECTORY_SEPARATOR, $res);
return (str_starts_with($res_str, 'phar:') ? str_replace(":\\\\","://", $res_str) : $res_str);
```

Once this is done, even complicated templates from PHARs are rendering just fine. 

I will try to create the appropriate Pull Request.

**Comment by dg** [comment]
Can you post a minimal code sample here when the problem occurs?

**Comment by Marian-Kechlibar** [comment]
For what purpose? A unit test to prevent relapse? Or is there any doubt whether the problem is real?

My smallest PHAR contains some 960 files and is full of IP that I cannot share, so I cannot provide it...

But the problem definitely happens and I had to apply that fix all around me. Basically, once you have a hierarchy of lattes where you derive anything from a layout, includes will start with phar:// and the normalizePath method will break them. _On Windows only_. On Linux, as the DIRECTORY_SEPARATOR is equal to /, the problem is trivially avoided.

**Comment by Marian-Kechlibar** [comment]
<img width="1920" alt="screenshot_bad_latte_address" src="https://github.com/user-attachments/assets/8bc2a43f-6f48-4c06-a701-6b9fda836fd6">

This is how it looks like once I revert my change.

**Comment by dg** [comment]
I'm sorry, but the "short of time" thing offends me. You think I don't have better things to do than work on solving your problem?
