### ISSUE TITLE
Feature Request: Allow auto-closing custom tags other than `block`

### ISSUE THREAD

**Issue by daun** [nette/latte#382]
I would love to extend the ability for auto-closing custom tags, not just `block`.

### Use case

The goal would be to create tags that work both as single tags that print html (`{custom}`) as well as tag pairs that wrap other html (`{custom}content{/custom}`). The differentiation between single tag and tag pair is significant in how the html is rendered.

### What I've tried

I've managed to check if the tag is self-closing (`{custom/}`), but auto-closing without a slash leads to an exception by the parser expecting an end tag. I've documented the case and my "progress" in [this Nette forum post](https://forum.nette.org/en/36708-how-to-check-if-a-tag-is-empty-or-self-closing).

### Current situation

Currently, there's a [hardcoded exception](https://github.com/nette/latte/blob/master/src/Latte/Compiler/TemplateParser.php#L346) for the `block` tag coded into the parser. There's also a [test for the autoclosing behavior](https://github.com/nette/latte/blob/master/tests/tags/block.autoclosing.phpt) of `block` which seems to be working great.

### Suggested API

A static property on the Tag class itself, e.g. `bool $allowsAutoclose` which defaults to `false`.

```php
/**
 * Tag that autocloses to allow both `{custom}` and `{custom}{/custom}`
 */
final class CustomNode extends StatementNode
{
    public string $name;

    public static bool $allowsAutoclose = true;

    public static function create(Tag $tag): \Generator;
}
```

**Comment by dg** [comment]
This was in Latte 2, but it turned out to be a thing that extremely complicates the parser, so it's not in Latte 3 anymore.

**Comment by daun** [comment]
@dg So the suggested API (check `$node::$allowsAutoclose` instead of the hardcoded check for the `block` node type) wouldn't work? I might not be seeing the full picture here, but looks like the logic is already in the parser and it's more of a question of allowing it for other tags.

**Comment by dg** [comment]
It's not about the API, but rather about how to program the parser so it can determine whether a tag used in the template is paired or not. This is very complex, and I'm definitely not going to dive into it.

**Comment by daun** [comment]
@dg Okay, so the issue is with having two or more of these in a template, and not being able to determine the nesting and pairing. Makes sense, thanks for the explanation.

It isn't very probable I'll ever get to this, but would you be open to a (well-tested) PR regarding this feature?

**Comment by daun** [comment]
I'll close this for now as there's no intent to add this :)
