### ISSUE TITLE
ApplicationLatte\Template can't be rendered on PHP >= 8.2

### ISSUE THREAD

**Issue by forrest79** [nette/latte#384]
Version: 3.0

### Bug Description
PHP 8.2 and greater disables creating dynamic properties on a class. If you want to use `ApplicationLatte\Template` instead of `ApplicationLatte\DefaultTemplate` - calling `render()` or `renderToString()` method with some parameter will fail, because dynamic property is creating and only `DefaultTemplate` has `AllowDynamicProperties` attribute, that allows this.

### Steps To Reproduce

```php
$template = new Nette\Bridges\ApplicationLatte\Template(new Latte\Engine());
$template->render('test.latte', ['name' => 'test']);
// Deprecated: Creation of dynamic property [Nette\Bridges\ApplicationLatte\Template]::$name is deprecated
```

### Expected Behavior
Template is correctly rendered.

### Possible Solution
Add `#[\AllowDynamicProperties]` also to `ApplicationLatte\Template` class? Don't use dynamic properties and use `__get/__set/__isset/__unset` instead of it?

**Comment by dg** [comment]
Update Nette/application https://doc.nette.org/cs/application#toc-instalace

**Comment by forrest79** [comment]
We're on the latest version - 3.2.6, docs says something about version 4, but I can't see this version on GitHub. How is this bug related to Nette\Application?

**Comment by dg** [comment]
It is related because these are classes from the `nette/application` package: https://github.com/nette/application/blob/master/src/Bridges/ApplicationLatte/Template.php

**Comment by forrest79** [comment]
Yea, I know, that `DefaultTemplate` works. We want to use `Template` for example for mails, where we don't need presenter properties presented on the `DefaultTemplate`. Right now, we have the own Template with `AllowDynamicProperties` attribute, but the `ApplicationLatte\Template` looks like it could be rendered - the errors is, from my point of view, unexpected here.

If `ApplicationLatte\Template` can't be rendered (with parameters), maybe it could be `abstract`?

**Comment by dg** [comment]
But what about people who don't want `AllowDynamicProperties`? What would they inherit from?

**Comment by forrest79** [comment]
Actually, I don't have an idea how to solve this :-( That's why I don't prepare a PR and just fill an issue. It looks to me like a bug, when code looks like it will do something and it will end with an error.

All possible solutions in my head are the BC break...
