### ISSUE TITLE
Combination of n:inner-block and {default} doesn't work

### ISSUE THREAD

**Issue by EdaCZ** [nette/latte#48]
Lets have following code in latte template:
```twig
{block content}
	{default $message = 'Default title'}

	<h1 n:inner-block="title">{$message}</h1>
```
Block #title is then included in layout template.

This code ends up with notice: "Undefined variable: message".

It is translated to:
```php
...
//
// block title
//
if (!function_exists($_b->blocks['title'][] = '_lb5d1553ada0_title')) { function _lb5d1553ada0_title($_b, $_args) { foreach ($_args as $__k => $__v) $$__k = $__v
    ;echo Latte\Runtime\Filters::escapeHtml($message, ENT_NOQUOTES) ;
}}
...
```
And dynamically defined variable $message is not known in block.

Is this a bug or I am missing something?

**Comment by JanTvrdik** [comment]
This is not a bug. The block in layout in rendered before the `$message` is declared. There is no way it could be available. This this:

~~~latte
{default $message = 'Default title'}
{block content}
    <h1 n:inner-block="title">{$message}</h1>
~~~

**Comment by EdaCZ** [comment]
Thank you. It works fine :+1: 

Closing...
