### ISSUE TITLE
{define} macro causes call for layout template

### ISSUE THREAD

**Issue by janlanger** [nette/latte#62]
Let's have this template:

```
{define #test}
bar
{/define}

foo
{include #test}
```

This template has no block, so I would expect no layout ("extend") template should be called. However, it is. On place where `{define}` is declared, there is an call to `rendeChildTemplate` as you can see here in compiled template https://gist.github.com/janlanger/6aba57cf214ee9d56ce1#file-compiled-php-L39

**Comment by paranoiq** [comment]
can be worked arround by adding `{layout null}` at the top

**Comment by milo** [comment]
This is expected behaviour.
