### ISSUE TITLE
Documentation: Missing "How to work with Latte?"

### ISSUE THREAD

**Issue by jkuchar** [nette/latte#63]
Hi!

As Latte is a separate package also documentation should provide me some guidance how to set it up and process my first Latte file.

Set up
=====
- install with composer <some params here>

Usage
=====

Preparing staff
-------------------

First create file from which you are going to use your template.

````php
$latte = new Latte\Latte("template.latte"); // just guessing
$latte->render();
````

And now let's move our template.latte file. And discover what a power is hidden in this library.

Diving into Latte's beauty
------------------------------

`<Current documentation>`

-----------------------------------------------

Makes that sense for you?

**Comment by JanTvrdik** [comment]
It is in readme

**Comment by jkuchar** [comment]
Oush! I've just been skimming thru readme and overlooked that. Pardon.
