### ISSUE TITLE
How to output a "{Welcome to Latte}" message?

### ISSUE THREAD

**Issue by taylorren** [nette/latte#67]
Hi

I want to literally output a <h2> heading like: **{Welcome to Latte}**, or **{{ WELCOME **

How to make that happen?

**Comment by Majkl578** [comment]
You can use `{l}` to output `{` and `{r}` for `}`. It's documented [here](http://doc.nette.org/en/2.3/default-macros).
Next time please ask on forums, this is an issue tracker.

**Comment by taylorren** [comment]
Thanks. Sorry for the confusion.

**Comment by dg** [comment]
@taylorren  Please use forum http://forum.nette.org/en/f47-latte for support.
