### ISSUE TITLE
Support for ?? operator

### ISSUE THREAD

**Issue by JanTvrdik** [nette/latte#68]
Latte should support `??` operarator in PHP 5, i.e. compile `{a() ?? $b() |noescape}` should be compiled to sth like:

~~~php
$tmp = a(); echo isset($tmp) ? $tmp : $b());
~~~

**Comment by dg** [comment]
Better is `echo is_null($tmp = a()) ? b() : $tmp;`

**Comment by milo** [comment]
Will be solved by PHP7.
