### ISSUE TITLE
Arguably wrong escaping of special characters in links outside of href attributes

### ISSUE THREAD

**Issue by josefsabl** [nette/latte#91]
Our problem is as follows. We send typical reset password e-mails using latte. And as anchors are removed in plain-text emails, our markup looks like this

```html
<a n:href='Sign:resetPassword, email="john.doe@gmail.com"'>reset password</a>

<p>
	Link not working?
	{link Sign:resetPassword, email="john.doe@gmail.com"}
</p>
```

Which generates this:

```html
<a href='https://www.app.cz/reset-password?email=john.doe%40gmail.com'>reset password</a>

<p>
	Link not working?
	https://www.app.cz/reset-password?email=john.doe%40gmail.com
</p>
```

Looks good? No!

As the second instance of link (under the "Link not working" line) is NOT an URL now but plain HTML, the at sign (@) should not be escaped. @ is just @ in HTML.

It works in most e-mail clients but not in all apparently as we see many "user john.doe%40gmail.com does not exist" errors in our log. Some of clients actually escape % to %25 so the resulting string is %2540 which browser interprets as %40 instead of @.

Is there some way to fix this? Noescape filter doesn't work (also I still want to escape ampersands correctly). Look like but to me.

PS: Hash protection has been omitted for clarity ;-)

**Comment by dg** [comment]
First instance is URL in HTML attribute, second instance is URL in HTML text. URL is always URL, no matter where it is placed.

**Comment by josefsabl** [comment]
Thanks, you got the point. I didn't realize the URL as such and specifically its parameters are not meant to be parsed and understood by people.

So that means this is the bug in mentioned e-mail clients. The hack to overcome this problem is to generate the link string outside latte and paste it in e. g. variable then.

**Comment by josefsabl** [comment]
Not sure but shouldn't noescape filter work in this case anyway?

**Comment by dg** [comment]
It has nothing to do with HTML escaping.

`@` is reserved character http://www.faqs.org/rfcs/rfc3986.html and must be encoded as `%25`. As workaround for buggy clients you can allow `/reset-password` to decode doubled-encoded entities.
