### ISSUE TITLE
Filter 'foo' is not defined bug - it just returns void

### ISSUE THREAD

**Issue by paveljanda** [nette/latte#92]
Let's have an example in template:

```php
{var $s = 'Hello'}
{$s|foo}
```

And filter defined:

```php
public static function foo($bar)
{
	if ($bar === 'Hello') {
		return $bar;
	}
}
```

That works well, but when we change the condition in filter to `if ($bar === 'Helloooo') {`, latte says that that **filter is not defined**.

**Comment by dg** [comment]
I am unable to reproduce it.

```php
$latte = new Latte\Engine;
$latte->setLoader(new Latte\Loaders\StringLoader);

function foo($bar)
{
    if ($bar === 'Hello') {
        return $bar;
    }
}

$latte->addFilter('foo', 'foo');

$latte->render(<<<'EOD'
{var $s = 'Helloa'}
{$s|foo}
EOD
, []);

```

**Comment by paveljanda** [comment]
I am able to reproduce it within nette fw:

1, composer create-project nette/web-project
2, Add ilters setup to config.neon:

	nette.latteFactory:
		setup:
			- addFilter(null, [\App\FooFilters(), loader])

3, Create filters class:

	namespace App;

	use Nette;

	class FooFilters extends Nette\Object
	{

		public static function loader($filter)
		{
			if (method_exists(__CLASS__, $filter)) {
				return call_user_func_array([__CLASS__, $filter], array_slice(func_get_args(), 1));
			}

			return NULL;
		}


		public static function foo($bar)
		{
			if ($bar === 'bar') {
				return $bar;
			}
		}

	}

4, Edit @layout.latte to look like this:

	{var $bar = 'bar'}
	{$bar|foo}

Now the filter works fine, but when you change `{var $bar = 'bar'}` to `{var $bar = 'bars'}`, than it stops working.

**Comment by hrach** [comment]
> For multifilters added via addFilter(NULL, ...) return empty string ''.

that's your solution, as David pointed out.

**Comment by paveljanda** [comment]
Oh i see the point. My mistake.
