### ISSUE TITLE
HTML Attribute names should not be quoted

### ISSUE THREAD

**Issue by talyian** [nette/latte#97]
When Latte generates HTML attribute names, they are currently escaped by quoting. This violates the HTML spec since attribute names cannot contain quotes. For example, when rendering the following template with data `["attr" => "a", "value" => "b"]`, 

    <tag {{$attr}}={{$value}} {{$attr}/>

Latte currently generates:

    <tag "a"="b" "a"/>

Instead, the properly formed HTML should be

    <tag a="b" a/>

To prevent adding an XSS vector, only valid HTML Attribute Names should be rendered.

**Comment by dg** [comment]
closed by #98
